/*
 * Copyright 2018 Vladimir Balun
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <iostream>
#include <Windows.h>
#include <GL/GL.h>

#define WGL_WGLEXT_PROTOTYPES
#include <GL/glext.h>
#include <GL/wglext.h>


GLvoid initOpenGL();


// GL_VERSION_1_2
#define glDrawRangeElements __glDrawRangeElements
#define glTexImage3D __glTexImage3D
#define glTexSubImage3D __glTexSubImage3D
#define glCopyTexSubImage3D __glCopyTexSubImage3D

extern PFNGLDRAWRANGEELEMENTSPROC __glDrawRangeElements;
extern PFNGLTEXIMAGE3DPROC __glTexImage3D;
extern PFNGLTEXSUBIMAGE3DPROC __glTexSubImage3D;
extern PFNGLCOPYTEXSUBIMAGE3DPROC __glCopyTexSubImage3D;


// GL_VERSION_1_3
#define glActiveTexture __glActiveTexture
#define glSampleCoverage __glSampleCoverage
#define glCompressedTexImage3D __glCompressedTexImage3D
#define glCompressedTexImage2D __glCompressedTexImage2D
#define glCompressedTexImage1D __glCompressedTexImage1D
#define glCompressedTexSubImage3D __glCompressedTexSubImage3D
#define glCompressedTexSubImage2D __glCompressedTexSubImage2D
#define glCompressedTexSubImage1D __glCompressedTexSubImage1D
#define glGetCompressedTexImage __glGetCompressedTexImage
#define glClientActiveTexture __glClientActiveTexture
#define glMultiTexCoord1d __glMultiTexCoord1d
#define glMultiTexCoord1dv __glMultiTexCoord1dv
#define glMultiTexCoord1f __glMultiTexCoord1f
#define glMultiTexCoord1fv __glMultiTexCoord1fv
#define glMultiTexCoord1i __glMultiTexCoord1i
#define glMultiTexCoord1iv __glMultiTexCoord1iv
#define glMultiTexCoord1s __glMultiTexCoord1s
#define glMultiTexCoord1sv __glMultiTexCoord1sv
#define glMultiTexCoord2d __glMultiTexCoord2d
#define glMultiTexCoord2dv __glMultiTexCoord2dv
#define glMultiTexCoord2f __glMultiTexCoord2f
#define glMultiTexCoord2fv __glMultiTexCoord2fv
#define glMultiTexCoord2i __glMultiTexCoord2i
#define glMultiTexCoord2iv __glMultiTexCoord2iv
#define glMultiTexCoord2s __glMultiTexCoord2s
#define glMultiTexCoord2sv __glMultiTexCoord2sv
#define glMultiTexCoord3d __glMultiTexCoord3d
#define glMultiTexCoord3dv __glMultiTexCoord3dv
#define glMultiTexCoord3f __glMultiTexCoord3f
#define glMultiTexCoord3fv __glMultiTexCoord3fv
#define glMultiTexCoord3i __glMultiTexCoord3i
#define glMultiTexCoord3iv __glMultiTexCoord3iv
#define glMultiTexCoord3s __glMultiTexCoord3s
#define glMultiTexCoord3sv __glMultiTexCoord3sv
#define glMultiTexCoord4d __glMultiTexCoord4d
#define glMultiTexCoord4dv __glMultiTexCoord4dv
#define glMultiTexCoord4f __glMultiTexCoord4f
#define glMultiTexCoord4fv __glMultiTexCoord4fv
#define glMultiTexCoord4i __glMultiTexCoord4i
#define glMultiTexCoord4iv __glMultiTexCoord4iv
#define glMultiTexCoord4s __glMultiTexCoord4s
#define glMultiTexCoord4sv __glMultiTexCoord4sv
#define glLoadTransposeMatrixf __glLoadTransposeMatrixf
#define glLoadTransposeMatrixd __glLoadTransposeMatrixd
#define glMultTransposeMatrixf __glMultTransposeMatrixf
#define glMultTransposeMatrixd __glMultTransposeMatrixd

extern PFNGLACTIVETEXTUREPROC __glActiveTexture;
extern PFNGLSAMPLECOVERAGEPROC __glSampleCoverage;
extern PFNGLCOMPRESSEDTEXIMAGE3DPROC __glCompressedTexImage3D;
extern PFNGLCOMPRESSEDTEXIMAGE2DPROC __glCompressedTexImage2D;
extern PFNGLCOMPRESSEDTEXIMAGE1DPROC __glCompressedTexImage1D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC __glCompressedTexSubImage3D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC __glCompressedTexSubImage2D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC __glCompressedTexSubImage1D;
extern PFNGLGETCOMPRESSEDTEXIMAGEPROC __glGetCompressedTexImage;
extern PFNGLCLIENTACTIVETEXTUREPROC __glClientActiveTexture;
extern PFNGLMULTITEXCOORD1DPROC __glMultiTexCoord1d;
extern PFNGLMULTITEXCOORD1DVPROC __glMultiTexCoord1dv;
extern PFNGLMULTITEXCOORD1FPROC __glMultiTexCoord1f;
extern PFNGLMULTITEXCOORD1FVPROC __glMultiTexCoord1fv;
extern PFNGLMULTITEXCOORD1IPROC __glMultiTexCoord1i;
extern PFNGLMULTITEXCOORD1IVPROC __glMultiTexCoord1iv;
extern PFNGLMULTITEXCOORD1SPROC __glMultiTexCoord1s;
extern PFNGLMULTITEXCOORD1SVPROC __glMultiTexCoord1sv;
extern PFNGLMULTITEXCOORD2DPROC __glMultiTexCoord2d;
extern PFNGLMULTITEXCOORD2DVPROC __glMultiTexCoord2dv;
extern PFNGLMULTITEXCOORD2FPROC __glMultiTexCoord2f;
extern PFNGLMULTITEXCOORD2FVPROC __glMultiTexCoord2fv;
extern PFNGLMULTITEXCOORD2IPROC __glMultiTexCoord2i;
extern PFNGLMULTITEXCOORD2IVPROC __glMultiTexCoord2iv;
extern PFNGLMULTITEXCOORD2SPROC __glMultiTexCoord2s;
extern PFNGLMULTITEXCOORD2SVPROC __glMultiTexCoord2sv;
extern PFNGLMULTITEXCOORD3DPROC __glMultiTexCoord3d;
extern PFNGLMULTITEXCOORD3DVPROC __glMultiTexCoord3dv;
extern PFNGLMULTITEXCOORD3FPROC __glMultiTexCoord3f;
extern PFNGLMULTITEXCOORD3FVPROC __glMultiTexCoord3fv;
extern PFNGLMULTITEXCOORD3IPROC __glMultiTexCoord3i;
extern PFNGLMULTITEXCOORD3IVPROC __glMultiTexCoord3iv;
extern PFNGLMULTITEXCOORD3SPROC __glMultiTexCoord3s;
extern PFNGLMULTITEXCOORD3SVPROC __glMultiTexCoord3sv;
extern PFNGLMULTITEXCOORD4DPROC __glMultiTexCoord4d;
extern PFNGLMULTITEXCOORD4DVPROC __glMultiTexCoord4dv;
extern PFNGLMULTITEXCOORD4FPROC __glMultiTexCoord4f;
extern PFNGLMULTITEXCOORD4FVPROC __glMultiTexCoord4fv;
extern PFNGLMULTITEXCOORD4IPROC __glMultiTexCoord4i;
extern PFNGLMULTITEXCOORD4IVPROC __glMultiTexCoord4iv;
extern PFNGLMULTITEXCOORD4SPROC __glMultiTexCoord4s;
extern PFNGLMULTITEXCOORD4SVPROC __glMultiTexCoord4sv;
extern PFNGLLOADTRANSPOSEMATRIXFPROC __glLoadTransposeMatrixf;
extern PFNGLLOADTRANSPOSEMATRIXDPROC __glLoadTransposeMatrixd;
extern PFNGLMULTTRANSPOSEMATRIXFPROC __glMultTransposeMatrixf;
extern PFNGLMULTTRANSPOSEMATRIXDPROC __glMultTransposeMatrixd;


// GL_VERSION_1_4
#define glBlendFuncSeparate __glBlendFuncSeparate
#define glMultiDrawArrays __glMultiDrawArrays
#define glMultiDrawElements __glMultiDrawElements
#define glPointParameterf __glPointParameterf
#define glPointParameterfv __glPointParameterfv
#define glPointParameteri __glPointParameteri
#define glPointParameteriv __glPointParameteriv
#define glFogCoordf __glFogCoordf
#define glFogCoordfv __glFogCoordfv
#define glFogCoordd __glFogCoordd
#define glFogCoorddv __glFogCoorddv
#define glFogCoordPointer __glFogCoordPointer
#define glSecondaryColor3b __glSecondaryColor3b
#define glSecondaryColor3bv __glSecondaryColor3bv
#define glSecondaryColor3d __glSecondaryColor3d
#define glSecondaryColor3dv __glSecondaryColor3dv
#define glSecondaryColor3f __glSecondaryColor3f
#define glSecondaryColor3fv __glSecondaryColor3fv
#define glSecondaryColor3i __glSecondaryColor3i
#define glSecondaryColor3iv __glSecondaryColor3iv
#define glSecondaryColor3s __glSecondaryColor3s
#define glSecondaryColor3sv __glSecondaryColor3sv
#define glSecondaryColor3ub __glSecondaryColor3ub
#define glSecondaryColor3ubv __glSecondaryColor3ubv
#define glSecondaryColor3ui __glSecondaryColor3ui
#define glSecondaryColor3uiv __glSecondaryColor3uiv
#define glSecondaryColor3us __glSecondaryColor3us
#define glSecondaryColor3usv __glSecondaryColor3usv
#define glSecondaryColorPointer __glSecondaryColorPointer
#define glWindowPos2d __glWindowPos2d
#define glWindowPos2dv __glWindowPos2dv
#define glWindowPos2f __glWindowPos2f
#define glWindowPos2fv __glWindowPos2fv
#define glWindowPos2i __glWindowPos2i
#define glWindowPos2iv __glWindowPos2iv
#define glWindowPos2s __glWindowPos2s
#define glWindowPos2sv __glWindowPos2sv
#define glWindowPos3d __glWindowPos3d
#define glWindowPos3dv __glWindowPos3dv
#define glWindowPos3f __glWindowPos3f
#define glWindowPos3fv __glWindowPos3fv
#define glWindowPos3i __glWindowPos3i
#define glWindowPos3iv __glWindowPos3iv
#define glWindowPos3s __glWindowPos3s
#define glWindowPos3sv __glWindowPos3sv
#define glBlendColor __glBlendColor
#define glBlendEquation __glBlendEquation

extern PFNGLBLENDFUNCSEPARATEPROC __glBlendFuncSeparate;
extern PFNGLMULTIDRAWARRAYSPROC __glMultiDrawArrays;
extern PFNGLMULTIDRAWELEMENTSPROC __glMultiDrawElements;
extern PFNGLPOINTPARAMETERFPROC __glPointParameterf;
extern PFNGLPOINTPARAMETERFVPROC __glPointParameterfv;
extern PFNGLPOINTPARAMETERIPROC __glPointParameteri;
extern PFNGLPOINTPARAMETERIVPROC __glPointParameteriv;
extern PFNGLFOGCOORDFPROC __glFogCoordf;
extern PFNGLFOGCOORDFVPROC __glFogCoordfv;
extern PFNGLFOGCOORDDPROC __glFogCoordd;
extern PFNGLFOGCOORDDVPROC __glFogCoorddv;
extern PFNGLFOGCOORDPOINTERPROC __glFogCoordPointer;
extern PFNGLSECONDARYCOLOR3BPROC __glSecondaryColor3b;
extern PFNGLSECONDARYCOLOR3BVPROC __glSecondaryColor3bv;
extern PFNGLSECONDARYCOLOR3DPROC __glSecondaryColor3d;
extern PFNGLSECONDARYCOLOR3DVPROC __glSecondaryColor3dv;
extern PFNGLSECONDARYCOLOR3FPROC __glSecondaryColor3f;
extern PFNGLSECONDARYCOLOR3FVPROC __glSecondaryColor3fv;
extern PFNGLSECONDARYCOLOR3IPROC __glSecondaryColor3i;
extern PFNGLSECONDARYCOLOR3IVPROC __glSecondaryColor3iv;
extern PFNGLSECONDARYCOLOR3SPROC __glSecondaryColor3s;
extern PFNGLSECONDARYCOLOR3SVPROC __glSecondaryColor3sv;
extern PFNGLSECONDARYCOLOR3UBPROC __glSecondaryColor3ub;
extern PFNGLSECONDARYCOLOR3UBVPROC __glSecondaryColor3ubv;
extern PFNGLSECONDARYCOLOR3UIPROC __glSecondaryColor3ui;
extern PFNGLSECONDARYCOLOR3UIVPROC __glSecondaryColor3uiv;
extern PFNGLSECONDARYCOLOR3USPROC __glSecondaryColor3us;
extern PFNGLSECONDARYCOLOR3USVPROC __glSecondaryColor3usv;
extern PFNGLSECONDARYCOLORPOINTERPROC __glSecondaryColorPointer;
extern PFNGLWINDOWPOS2DPROC __glWindowPos2d;
extern PFNGLWINDOWPOS2DVPROC __glWindowPos2dv;
extern PFNGLWINDOWPOS2FPROC __glWindowPos2f;
extern PFNGLWINDOWPOS2FVPROC __glWindowPos2fv;
extern PFNGLWINDOWPOS2IPROC __glWindowPos2i;
extern PFNGLWINDOWPOS2IVPROC __glWindowPos2iv;
extern PFNGLWINDOWPOS2SPROC __glWindowPos2s;
extern PFNGLWINDOWPOS2SVPROC __glWindowPos2sv;
extern PFNGLWINDOWPOS3DPROC __glWindowPos3d;
extern PFNGLWINDOWPOS3DVPROC __glWindowPos3dv;
extern PFNGLWINDOWPOS3FPROC __glWindowPos3f;
extern PFNGLWINDOWPOS3FVPROC __glWindowPos3fv;
extern PFNGLWINDOWPOS3IPROC __glWindowPos3i;
extern PFNGLWINDOWPOS3IVPROC __glWindowPos3iv;
extern PFNGLWINDOWPOS3SPROC __glWindowPos3s;
extern PFNGLWINDOWPOS3SVPROC __glWindowPos3sv;
extern PFNGLBLENDCOLORPROC __glBlendColor;
extern PFNGLBLENDEQUATIONPROC __glBlendEquation;


// GL_VERSION_1_5
#define glGenQueries __glGenQueries
#define glDeleteQueries __glDeleteQueries
#define glIsQuery __glIsQuery
#define glBeginQuery __glBeginQuery
#define glEndQuery __glEndQuery
#define glGetQueryiv __glGetQueryiv
#define glGetQueryObjectiv __glGetQueryObjectiv
#define glGetQueryObjectuiv __glGetQueryObjectuiv
#define glBindBuffer __glBindBuffer
#define glDeleteBuffers __glDeleteBuffers
#define glGenBuffers __glGenBuffers
#define glIsBuffer __glIsBuffer
#define glBufferData __glBufferData
#define glBufferSubData __glBufferSubData
#define glGetBufferSubData __glGetBufferSubData
#define glMapBuffer __glMapBuffer
#define glUnmapBuffer __glUnmapBuffer
#define glGetBufferParameteriv __glGetBufferParameteriv
#define glGetBufferPointerv __glGetBufferPointerv

extern PFNGLGENQUERIESPROC __glGenQueries;
extern PFNGLDELETEQUERIESPROC __glDeleteQueries;
extern PFNGLISQUERYPROC __glIsQuery;
extern PFNGLBEGINQUERYPROC __glBeginQuery;
extern PFNGLENDQUERYPROC __glEndQuery;
extern PFNGLGETQUERYIVPROC __glGetQueryiv;
extern PFNGLGETQUERYOBJECTIVPROC __glGetQueryObjectiv;
extern PFNGLGETQUERYOBJECTUIVPROC __glGetQueryObjectuiv;
extern PFNGLBINDBUFFERPROC __glBindBuffer;
extern PFNGLDELETEBUFFERSPROC __glDeleteBuffers;
extern PFNGLGENBUFFERSPROC __glGenBuffers;
extern PFNGLISBUFFERPROC __glIsBuffer;
extern PFNGLBUFFERDATAPROC __glBufferData;
extern PFNGLBUFFERSUBDATAPROC __glBufferSubData;
extern PFNGLGETBUFFERSUBDATAPROC __glGetBufferSubData;
extern PFNGLMAPBUFFERPROC __glMapBuffer;
extern PFNGLUNMAPBUFFERPROC __glUnmapBuffer;
extern PFNGLGETBUFFERPARAMETERIVPROC __glGetBufferParameteriv;
extern PFNGLGETBUFFERPOINTERVPROC __glGetBufferPointerv;


// GL_VERSION_2_0
#define glBlendEquationSeparate __glBlendEquationSeparate
#define glDrawBuffers __glDrawBuffers
#define glStencilOpSeparate __glStencilOpSeparate
#define glStencilFuncSeparate __glStencilFuncSeparate
#define glStencilMaskSeparate __glStencilMaskSeparate
#define glAttachShader __glAttachShader
#define glBindAttribLocation __glBindAttribLocation
#define glCompileShader __glCompileShader
#define glCreateProgram __glCreateProgram
#define glCreateShader __glCreateShader
#define glDeleteProgram __glDeleteProgram
#define glDeleteShader __glDeleteShader
#define glDetachShader __glDetachShader
#define glDisableVertexAttribArray __glDisableVertexAttribArray
#define glEnableVertexAttribArray __glEnableVertexAttribArray
#define glGetActiveAttrib __glGetActiveAttrib
#define glGetActiveUniform __glGetActiveUniform
#define glGetAttachedShaders __glGetAttachedShaders
#define glGetAttribLocation __glGetAttribLocation
#define glGetProgramiv __glGetProgramiv
#define glGetProgramInfoLog __glGetProgramInfoLog
#define glGetShaderiv __glGetShaderiv
#define glGetShaderInfoLog __glGetShaderInfoLog
#define glGetShaderSource __glGetShaderSource
#define glGetUniformLocation __glGetUniformLocation
#define glGetUniformfv __glGetUniformfv
#define glGetUniformiv __glGetUniformiv
#define glGetVertexAttribdv __glGetVertexAttribdv
#define glGetVertexAttribfv __glGetVertexAttribfv
#define glGetVertexAttribiv __glGetVertexAttribiv
#define glGetVertexAttribPointerv __glGetVertexAttribPointerv
#define glIsProgram __glIsProgram
#define glIsShader __glIsShader
#define glLinkProgram __glLinkProgram
#define glShaderSource __glShaderSource
#define glUseProgram __glUseProgram
#define glUniform1f __glUniform1f
#define glUniform2f __glUniform2f
#define glUniform3f __glUniform3f
#define glUniform4f __glUniform4f
#define glUniform1i __glUniform1i
#define glUniform2i __glUniform2i
#define glUniform3i __glUniform3i
#define glUniform4i __glUniform4i
#define glUniform1fv __glUniform1fv
#define glUniform2fv __glUniform2fv
#define glUniform3fv __glUniform3fv
#define glUniform4fv __glUniform4fv
#define glUniform1iv __glUniform1iv
#define glUniform2iv __glUniform2iv
#define glUniform3iv __glUniform3iv
#define glUniform4iv __glUniform4iv
#define glUniformMatrix2fv __glUniformMatrix2fv
#define glUniformMatrix3fv __glUniformMatrix3fv
#define glUniformMatrix4fv __glUniformMatrix4fv
#define glValidateProgram __glValidateProgram
#define glVertexAttrib1d __glVertexAttrib1d
#define glVertexAttrib1dv __glVertexAttrib1dv
#define glVertexAttrib1f __glVertexAttrib1f
#define glVertexAttrib1fv __glVertexAttrib1fv
#define glVertexAttrib1s __glVertexAttrib1s
#define glVertexAttrib1sv __glVertexAttrib1sv
#define glVertexAttrib2d __glVertexAttrib2d
#define glVertexAttrib2dv __glVertexAttrib2dv
#define glVertexAttrib2f __glVertexAttrib2f
#define glVertexAttrib2fv __glVertexAttrib2fv
#define glVertexAttrib2s __glVertexAttrib2s
#define glVertexAttrib2sv __glVertexAttrib2sv
#define glVertexAttrib3d __glVertexAttrib3d
#define glVertexAttrib3dv __glVertexAttrib3dv
#define glVertexAttrib3f __glVertexAttrib3f
#define glVertexAttrib3fv __glVertexAttrib3fv
#define glVertexAttrib3s __glVertexAttrib3s
#define glVertexAttrib3sv __glVertexAttrib3sv
#define glVertexAttrib4Nbv __glVertexAttrib4Nbv
#define glVertexAttrib4Niv __glVertexAttrib4Niv
#define glVertexAttrib4Nsv __glVertexAttrib4Nsv
#define glVertexAttrib4Nub __glVertexAttrib4Nub
#define glVertexAttrib4Nubv __glVertexAttrib4Nubv
#define glVertexAttrib4Nuiv __glVertexAttrib4Nuiv
#define glVertexAttrib4Nusv __glVertexAttrib4Nusv
#define glVertexAttrib4bv __glVertexAttrib4bv
#define glVertexAttrib4d __glVertexAttrib4d
#define glVertexAttrib4dv __glVertexAttrib4dv
#define glVertexAttrib4f __glVertexAttrib4f
#define glVertexAttrib4fv __glVertexAttrib4fv
#define glVertexAttrib4iv __glVertexAttrib4iv
#define glVertexAttrib4s __glVertexAttrib4s
#define glVertexAttrib4sv __glVertexAttrib4sv
#define glVertexAttrib4ubv __glVertexAttrib4ubv
#define glVertexAttrib4uiv __glVertexAttrib4uiv
#define glVertexAttrib4usv __glVertexAttrib4usv
#define glVertexAttribPointer __glVertexAttribPointer

extern PFNGLBLENDEQUATIONSEPARATEPROC __glBlendEquationSeparate;
extern PFNGLDRAWBUFFERSPROC __glDrawBuffers;
extern PFNGLSTENCILOPSEPARATEPROC __glStencilOpSeparate;
extern PFNGLSTENCILFUNCSEPARATEPROC __glStencilFuncSeparate;
extern PFNGLSTENCILMASKSEPARATEPROC __glStencilMaskSeparate;
extern PFNGLATTACHSHADERPROC __glAttachShader;
extern PFNGLBINDATTRIBLOCATIONPROC __glBindAttribLocation;
extern PFNGLCOMPILESHADERPROC __glCompileShader;
extern PFNGLCREATEPROGRAMPROC __glCreateProgram;
extern PFNGLCREATESHADERPROC __glCreateShader;
extern PFNGLDELETEPROGRAMPROC __glDeleteProgram;
extern PFNGLDELETESHADERPROC __glDeleteShader;
extern PFNGLDETACHSHADERPROC __glDetachShader;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC __glDisableVertexAttribArray;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC __glEnableVertexAttribArray;
extern PFNGLGETACTIVEATTRIBPROC __glGetActiveAttrib;
extern PFNGLGETACTIVEUNIFORMPROC __glGetActiveUniform;
extern PFNGLGETATTACHEDSHADERSPROC __glGetAttachedShaders;
extern PFNGLGETATTRIBLOCATIONPROC __glGetAttribLocation;
extern PFNGLGETPROGRAMIVPROC __glGetProgramiv;
extern PFNGLGETPROGRAMINFOLOGPROC __glGetProgramInfoLog;
extern PFNGLGETSHADERIVPROC __glGetShaderiv;
extern PFNGLGETSHADERINFOLOGPROC __glGetShaderInfoLog;
extern PFNGLGETSHADERSOURCEPROC __glGetShaderSource;
extern PFNGLGETUNIFORMLOCATIONPROC __glGetUniformLocation;
extern PFNGLGETUNIFORMFVPROC __glGetUniformfv;
extern PFNGLGETUNIFORMIVPROC __glGetUniformiv;
extern PFNGLGETVERTEXATTRIBDVPROC __glGetVertexAttribdv;
extern PFNGLGETVERTEXATTRIBFVPROC __glGetVertexAttribfv;
extern PFNGLGETVERTEXATTRIBIVPROC __glGetVertexAttribiv;
extern PFNGLGETVERTEXATTRIBPOINTERVPROC __glGetVertexAttribPointerv;
extern PFNGLISPROGRAMPROC __glIsProgram;
extern PFNGLISSHADERPROC __glIsShader;
extern PFNGLLINKPROGRAMPROC __glLinkProgram;
extern PFNGLSHADERSOURCEPROC __glShaderSource;
extern PFNGLUSEPROGRAMPROC __glUseProgram;
extern PFNGLUNIFORM1FPROC __glUniform1f;
extern PFNGLUNIFORM2FPROC __glUniform2f;
extern PFNGLUNIFORM3FPROC __glUniform3f;
extern PFNGLUNIFORM4FPROC __glUniform4f;
extern PFNGLUNIFORM1IPROC __glUniform1i;
extern PFNGLUNIFORM2IPROC __glUniform2i;
extern PFNGLUNIFORM3IPROC __glUniform3i;
extern PFNGLUNIFORM4IPROC __glUniform4i;
extern PFNGLUNIFORM1FVPROC __glUniform1fv;
extern PFNGLUNIFORM2FVPROC __glUniform2fv;
extern PFNGLUNIFORM3FVPROC __glUniform3fv;
extern PFNGLUNIFORM4FVPROC __glUniform4fv;
extern PFNGLUNIFORM1IVPROC __glUniform1iv;
extern PFNGLUNIFORM2IVPROC __glUniform2iv;
extern PFNGLUNIFORM3IVPROC __glUniform3iv;
extern PFNGLUNIFORM4IVPROC __glUniform4iv;
extern PFNGLUNIFORMMATRIX2FVPROC __glUniformMatrix2fv;
extern PFNGLUNIFORMMATRIX3FVPROC __glUniformMatrix3fv;
extern PFNGLUNIFORMMATRIX4FVPROC __glUniformMatrix4fv;
extern PFNGLVALIDATEPROGRAMPROC __glValidateProgram;
extern PFNGLVERTEXATTRIB1DPROC __glVertexAttrib1d;
extern PFNGLVERTEXATTRIB1DVPROC __glVertexAttrib1dv;
extern PFNGLVERTEXATTRIB1FPROC __glVertexAttrib1f;
extern PFNGLVERTEXATTRIB1FVPROC __glVertexAttrib1fv;
extern PFNGLVERTEXATTRIB1SPROC __glVertexAttrib1s;
extern PFNGLVERTEXATTRIB1SVPROC __glVertexAttrib1sv;
extern PFNGLVERTEXATTRIB2DPROC __glVertexAttrib2d;
extern PFNGLVERTEXATTRIB2DVPROC __glVertexAttrib2dv;
extern PFNGLVERTEXATTRIB2FPROC __glVertexAttrib2f;
extern PFNGLVERTEXATTRIB2FVPROC __glVertexAttrib2fv;
extern PFNGLVERTEXATTRIB2SPROC __glVertexAttrib2s;
extern PFNGLVERTEXATTRIB2SVPROC __glVertexAttrib2sv;
extern PFNGLVERTEXATTRIB3DPROC __glVertexAttrib3d;
extern PFNGLVERTEXATTRIB3DVPROC __glVertexAttrib3dv;
extern PFNGLVERTEXATTRIB3FPROC __glVertexAttrib3f;
extern PFNGLVERTEXATTRIB3FVPROC __glVertexAttrib3fv;
extern PFNGLVERTEXATTRIB3SPROC __glVertexAttrib3s;
extern PFNGLVERTEXATTRIB3SVPROC __glVertexAttrib3sv;
extern PFNGLVERTEXATTRIB4NBVPROC __glVertexAttrib4Nbv;
extern PFNGLVERTEXATTRIB4NIVPROC __glVertexAttrib4Niv;
extern PFNGLVERTEXATTRIB4NSVPROC __glVertexAttrib4Nsv;
extern PFNGLVERTEXATTRIB4NUBPROC __glVertexAttrib4Nub;
extern PFNGLVERTEXATTRIB4NUBVPROC __glVertexAttrib4Nubv;
extern PFNGLVERTEXATTRIB4NUIVPROC __glVertexAttrib4Nuiv;
extern PFNGLVERTEXATTRIB4NUSVPROC __glVertexAttrib4Nusv;
extern PFNGLVERTEXATTRIB4BVPROC __glVertexAttrib4bv;
extern PFNGLVERTEXATTRIB4DPROC __glVertexAttrib4d;
extern PFNGLVERTEXATTRIB4DVPROC __glVertexAttrib4dv;
extern PFNGLVERTEXATTRIB4FPROC __glVertexAttrib4f;
extern PFNGLVERTEXATTRIB4FVPROC __glVertexAttrib4fv;
extern PFNGLVERTEXATTRIB4IVPROC __glVertexAttrib4iv;
extern PFNGLVERTEXATTRIB4SPROC __glVertexAttrib4s;
extern PFNGLVERTEXATTRIB4SVPROC __glVertexAttrib4sv;
extern PFNGLVERTEXATTRIB4UBVPROC __glVertexAttrib4ubv;
extern PFNGLVERTEXATTRIB4UIVPROC __glVertexAttrib4uiv;
extern PFNGLVERTEXATTRIB4USVPROC __glVertexAttrib4usv;
extern PFNGLVERTEXATTRIBPOINTERPROC __glVertexAttribPointer;


// GL_VERSION_2_1
#define glUniformMatrix2x3fv __glUniformMatrix2x3fv
#define glUniformMatrix3x2fv __glUniformMatrix3x2fv
#define glUniformMatrix2x4fv __glUniformMatrix2x4fv
#define glUniformMatrix4x2fv __glUniformMatrix4x2fv
#define glUniformMatrix3x4fv __glUniformMatrix3x4fv
#define glUniformMatrix4x3fv __glUniformMatrix4x3fv

extern PFNGLUNIFORMMATRIX2X3FVPROC __glUniformMatrix2x3fv;
extern PFNGLUNIFORMMATRIX3X2FVPROC __glUniformMatrix3x2fv;
extern PFNGLUNIFORMMATRIX2X4FVPROC __glUniformMatrix2x4fv;
extern PFNGLUNIFORMMATRIX4X2FVPROC __glUniformMatrix4x2fv;
extern PFNGLUNIFORMMATRIX3X4FVPROC __glUniformMatrix3x4fv;
extern PFNGLUNIFORMMATRIX4X3FVPROC __glUniformMatrix4x3fv;


//  GL_VERSION_3_0
#define glColorMaski __glColorMaski
#define glGetBooleani_v __glGetBooleani_v
#define glGetIntegeri_v __glGetIntegeri_v
#define glEnablei __glEnablei
#define glDisablei __glDisablei
#define glIsEnabledi __glIsEnabledi
#define glBeginTransformFeedback __glBeginTransformFeedback
#define glEndTransformFeedback __glEndTransformFeedback
#define glBindBufferRange __glBindBufferRange
#define glBindBufferBase __glBindBufferBase
#define glTransformFeedbackVaryings __glTransformFeedbackVaryings
#define glGetTransformFeedbackVarying __glGetTransformFeedbackVarying
#define glClampColor __glClampColor
#define glBeginConditionalRender __glBeginConditionalRender
#define glEndConditionalRender __glEndConditionalRender
#define glVertexAttribIPointer __glVertexAttribIPointer
#define glGetVertexAttribIiv __glGetVertexAttribIiv
#define glGetVertexAttribIuiv __glGetVertexAttribIuiv
#define glVertexAttribI1i __glVertexAttribI1i
#define glVertexAttribI2i __glVertexAttribI2i
#define glVertexAttribI3i __glVertexAttribI3i
#define glVertexAttribI4i __glVertexAttribI4i
#define glVertexAttribI1ui __glVertexAttribI1ui
#define glVertexAttribI2ui __glVertexAttribI2ui
#define glVertexAttribI3ui __glVertexAttribI3ui
#define glVertexAttribI4ui __glVertexAttribI4ui
#define glVertexAttribI1iv __glVertexAttribI1iv
#define glVertexAttribI2iv __glVertexAttribI2iv
#define glVertexAttribI3iv __glVertexAttribI3iv
#define glVertexAttribI4iv __glVertexAttribI4iv
#define glVertexAttribI1uiv __glVertexAttribI1uiv
#define glVertexAttribI2uiv __glVertexAttribI2uiv
#define glVertexAttribI3uiv __glVertexAttribI3uiv
#define glVertexAttribI4uiv __glVertexAttribI4uiv
#define glVertexAttribI4bv __glVertexAttribI4bv
#define glVertexAttribI4sv __glVertexAttribI4sv
#define glVertexAttribI4ubv __glVertexAttribI4ubv
#define glVertexAttribI4usv __glVertexAttribI4usv
#define glGetUniformuiv __glGetUniformuiv
#define glBindFragDataLocation __glBindFragDataLocation
#define glGetFragDataLocation __glGetFragDataLocation
#define glUniform1ui __glUniform1ui
#define glUniform2ui __glUniform2ui
#define glUniform3ui __glUniform3ui
#define glUniform4ui __glUniform4ui
#define glUniform1uiv __glUniform1uiv
#define glUniform2uiv __glUniform2uiv
#define glUniform3uiv __glUniform3uiv
#define glUniform4uiv __glUniform4uiv
#define glTexParameterIiv __glTexParameterIiv
#define glTexParameterIuiv __glTexParameterIuiv
#define glGetTexParameterIiv __glGetTexParameterIiv
#define glGetTexParameterIuiv __glGetTexParameterIuiv
#define glClearBufferiv __glClearBufferiv
#define glClearBufferuiv __glClearBufferuiv
#define glClearBufferfv __glClearBufferfv
#define glClearBufferfi __glClearBufferfi
#define glGetStringi __glGetStringi
#define glIsRenderbuffer __glIsRenderbuffer
#define glBindRenderbuffer __glBindRenderbuffer
#define glDeleteRenderbuffers __glDeleteRenderbuffers
#define glGenRenderbuffers __glGenRenderbuffers
#define glRenderbufferStorage __glRenderbufferStorage
#define glGetRenderbufferParameteriv __glGetRenderbufferParameteriv
#define glIsFramebuffer __glIsFramebuffer
#define glBindFramebuffer __glBindFramebuffer
#define glDeleteFramebuffers __glDeleteFramebuffers
#define glGenFramebuffers __glGenFramebuffers
#define glCheckFramebufferStatus __glCheckFramebufferStatus
#define glFramebufferTexture1D __glFramebufferTexture1D
#define glFramebufferTexture2D __glFramebufferTexture2D
#define glFramebufferTexture3D __glFramebufferTexture3D
#define glFramebufferRenderbuffer __glFramebufferRenderbuffer
#define glGetFramebufferAttachmentParameteriv __glGetFramebufferAttachmentParameteriv
#define glGenerateMipmap __glGenerateMipmap
#define glBlitFramebuffer __glBlitFramebuffer
#define glRenderbufferStorageMultisample __glRenderbufferStorageMultisample
#define glFramebufferTextureLayer __glFramebufferTextureLayer
#define glMapBufferRange __glMapBufferRange
#define glFlushMappedBufferRange __glFlushMappedBufferRange
#define glBindVertexArray __glBindVertexArray
#define glDeleteVertexArrays __glDeleteVertexArrays
#define glGenVertexArrays __glGenVertexArrays
#define glIsVertexArray __glIsVertexArray

extern PFNGLCOLORMASKIPROC __glColorMaski;
extern PFNGLGETBOOLEANI_VPROC __glGetBooleani_v;
extern PFNGLGETINTEGERI_VPROC __glGetIntegeri_v;
extern PFNGLENABLEIPROC __glEnablei;
extern PFNGLDISABLEIPROC __glDisablei;
extern PFNGLISENABLEDIPROC __glIsEnabledi;
extern PFNGLBEGINTRANSFORMFEEDBACKPROC __glBeginTransformFeedback;
extern PFNGLENDTRANSFORMFEEDBACKPROC __glEndTransformFeedback;
extern PFNGLBINDBUFFERRANGEPROC __glBindBufferRange;
extern PFNGLBINDBUFFERBASEPROC __glBindBufferBase;
extern PFNGLTRANSFORMFEEDBACKVARYINGSPROC __glTransformFeedbackVaryings;
extern PFNGLGETTRANSFORMFEEDBACKVARYINGPROC __glGetTransformFeedbackVarying;
extern PFNGLCLAMPCOLORPROC __glClampColor;
extern PFNGLBEGINCONDITIONALRENDERPROC __glBeginConditionalRender;
extern PFNGLENDCONDITIONALRENDERPROC __glEndConditionalRender;
extern PFNGLVERTEXATTRIBIPOINTERPROC __glVertexAttribIPointer;
extern PFNGLGETVERTEXATTRIBIIVPROC __glGetVertexAttribIiv;
extern PFNGLGETVERTEXATTRIBIUIVPROC __glGetVertexAttribIuiv;
extern PFNGLVERTEXATTRIBI1IPROC __glVertexAttribI1i;
extern PFNGLVERTEXATTRIBI2IPROC __glVertexAttribI2i;
extern PFNGLVERTEXATTRIBI3IPROC __glVertexAttribI3i;
extern PFNGLVERTEXATTRIBI4IPROC __glVertexAttribI4i;
extern PFNGLVERTEXATTRIBI1UIPROC __glVertexAttribI1ui;
extern PFNGLVERTEXATTRIBI2UIPROC __glVertexAttribI2ui;
extern PFNGLVERTEXATTRIBI3UIPROC __glVertexAttribI3ui;
extern PFNGLVERTEXATTRIBI4UIPROC __glVertexAttribI4ui;
extern PFNGLVERTEXATTRIBI1IVPROC __glVertexAttribI1iv;
extern PFNGLVERTEXATTRIBI2IVPROC __glVertexAttribI2iv;
extern PFNGLVERTEXATTRIBI3IVPROC __glVertexAttribI3iv;
extern PFNGLVERTEXATTRIBI4IVPROC __glVertexAttribI4iv;
extern PFNGLVERTEXATTRIBI1UIVPROC __glVertexAttribI1uiv;
extern PFNGLVERTEXATTRIBI2UIVPROC __glVertexAttribI2uiv;
extern PFNGLVERTEXATTRIBI3UIVPROC __glVertexAttribI3uiv;
extern PFNGLVERTEXATTRIBI4UIVPROC __glVertexAttribI4uiv;
extern PFNGLVERTEXATTRIBI4BVPROC __glVertexAttribI4bv;
extern PFNGLVERTEXATTRIBI4SVPROC __glVertexAttribI4sv;
extern PFNGLVERTEXATTRIBI4UBVPROC __glVertexAttribI4ubv;
extern PFNGLVERTEXATTRIBI4USVPROC __glVertexAttribI4usv;
extern PFNGLGETUNIFORMUIVPROC __glGetUniformuiv;
extern PFNGLBINDFRAGDATALOCATIONPROC __glBindFragDataLocation;
extern PFNGLGETFRAGDATALOCATIONPROC __glGetFragDataLocation;
extern PFNGLUNIFORM1UIPROC __glUniform1ui;
extern PFNGLUNIFORM2UIPROC __glUniform2ui;
extern PFNGLUNIFORM3UIPROC __glUniform3ui;
extern PFNGLUNIFORM4UIPROC __glUniform4ui;
extern PFNGLUNIFORM1UIVPROC __glUniform1uiv;
extern PFNGLUNIFORM2UIVPROC __glUniform2uiv;
extern PFNGLUNIFORM3UIVPROC __glUniform3uiv;
extern PFNGLUNIFORM4UIVPROC __glUniform4uiv;
extern PFNGLTEXPARAMETERIIVPROC __glTexParameterIiv;
extern PFNGLTEXPARAMETERIUIVPROC __glTexParameterIuiv;
extern PFNGLGETTEXPARAMETERIIVPROC __glGetTexParameterIiv;
extern PFNGLGETTEXPARAMETERIUIVPROC __glGetTexParameterIuiv;
extern PFNGLCLEARBUFFERIVPROC __glClearBufferiv;
extern PFNGLCLEARBUFFERUIVPROC __glClearBufferuiv;
extern PFNGLCLEARBUFFERFVPROC __glClearBufferfv;
extern PFNGLCLEARBUFFERFIPROC __glClearBufferfi;
extern PFNGLGETSTRINGIPROC __glGetStringi;
extern PFNGLISRENDERBUFFERPROC __glIsRenderbuffer;
extern PFNGLBINDRENDERBUFFERPROC __glBindRenderbuffer;
extern PFNGLDELETERENDERBUFFERSPROC __glDeleteRenderbuffers;
extern PFNGLGENRENDERBUFFERSPROC __glGenRenderbuffers;
extern PFNGLRENDERBUFFERSTORAGEPROC __glRenderbufferStorage;
extern PFNGLGETRENDERBUFFERPARAMETERIVPROC __glGetRenderbufferParameteriv;
extern PFNGLISFRAMEBUFFERPROC __glIsFramebuffer;
extern PFNGLBINDFRAMEBUFFERPROC __glBindFramebuffer;
extern PFNGLDELETEFRAMEBUFFERSPROC __glDeleteFramebuffers;
extern PFNGLGENFRAMEBUFFERSPROC __glGenFramebuffers;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC __glCheckFramebufferStatus;
extern PFNGLFRAMEBUFFERTEXTURE1DPROC __glFramebufferTexture1D;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC __glFramebufferTexture2D;
extern PFNGLFRAMEBUFFERTEXTURE3DPROC __glFramebufferTexture3D;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC __glFramebufferRenderbuffer;
extern PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC __glGetFramebufferAttachmentParameteriv;
extern PFNGLGENERATEMIPMAPPROC __glGenerateMipmap;
extern PFNGLBLITFRAMEBUFFERPROC __glBlitFramebuffer;
extern PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC __glRenderbufferStorageMultisample;
extern PFNGLFRAMEBUFFERTEXTURELAYERPROC __glFramebufferTextureLayer;
extern PFNGLMAPBUFFERRANGEPROC __glMapBufferRange;
extern PFNGLFLUSHMAPPEDBUFFERRANGEPROC __glFlushMappedBufferRange;
extern PFNGLBINDVERTEXARRAYPROC __glBindVertexArray;
extern PFNGLDELETEVERTEXARRAYSPROC __glDeleteVertexArrays;
extern PFNGLGENVERTEXARRAYSPROC __glGenVertexArrays;
extern PFNGLISVERTEXARRAYPROC __glIsVertexArray;


// GL_VERSION_3_1
#define glDrawArraysInstanced __glDrawArraysInstanced
#define glDrawElementsInstanced __glDrawElementsInstanced
#define glTexBuffer __glTexBuffer
#define glPrimitiveRestartIndex __glPrimitiveRestartIndex
#define glCopyBufferSubData __glCopyBufferSubData
#define glGetUniformIndices __glGetUniformIndices
#define glGetActiveUniformsiv __glGetActiveUniformsiv
#define glGetActiveUniformName __glGetActiveUniformName
#define glGetUniformBlockIndex __glGetUniformBlockIndex
#define glGetActiveUniformBlockiv __glGetActiveUniformBlockiv
#define glGetActiveUniformBlockName __glGetActiveUniformBlockName
#define glUniformBlockBinding __glUniformBlockBinding

extern PFNGLDRAWARRAYSINSTANCEDPROC __glDrawArraysInstanced;
extern PFNGLDRAWELEMENTSINSTANCEDPROC __glDrawElementsInstanced;
extern PFNGLTEXBUFFERPROC __glTexBuffer;
extern PFNGLPRIMITIVERESTARTINDEXPROC __glPrimitiveRestartIndex;
extern PFNGLCOPYBUFFERSUBDATAPROC __glCopyBufferSubData;
extern PFNGLGETUNIFORMINDICESPROC __glGetUniformIndices;
extern PFNGLGETACTIVEUNIFORMSIVPROC __glGetActiveUniformsiv;
extern PFNGLGETACTIVEUNIFORMNAMEPROC __glGetActiveUniformName;
extern PFNGLGETUNIFORMBLOCKINDEXPROC __glGetUniformBlockIndex;
extern PFNGLGETACTIVEUNIFORMBLOCKIVPROC __glGetActiveUniformBlockiv;
extern PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC __glGetActiveUniformBlockName;
extern PFNGLUNIFORMBLOCKBINDINGPROC __glUniformBlockBinding;


// GL_VERSION_3_2
#define glDrawElementsBaseVertex __glDrawElementsBaseVertex
#define glDrawRangeElementsBaseVertex __glDrawRangeElementsBaseVertex
#define glDrawElementsInstancedBaseVertex __glDrawElementsInstancedBaseVertex
#define glMultiDrawElementsBaseVertex __glMultiDrawElementsBaseVertex
#define glProvokingVertex __glProvokingVertex
#define glFenceSync __glFenceSync
#define glIsSync __glIsSync
#define glDeleteSync __glDeleteSync
#define glClientWaitSync __glClientWaitSync
#define glWaitSync __glWaitSync
#define glGetInteger64v __glGetInteger64v
#define glGetSynciv __glGetSynciv
#define glGetInteger64i_v __glGetInteger64i_v
#define glGetBufferParameteri64v __glGetBufferParameteri64v
#define glFramebufferTexture __glFramebufferTexture
#define glTexImage2DMultisample __glTexImage2DMultisample
#define glTexImage3DMultisample __glTexImage3DMultisample
#define glGetMultisamplefv __glGetMultisamplefv
#define glSampleMaski __glSampleMaski

extern PFNGLDRAWELEMENTSBASEVERTEXPROC __glDrawElementsBaseVertex;
extern PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC __glDrawRangeElementsBaseVertex;
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC __glDrawElementsInstancedBaseVertex;
extern PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC __glMultiDrawElementsBaseVertex;
extern PFNGLPROVOKINGVERTEXPROC __glProvokingVertex;
extern PFNGLFENCESYNCPROC __glFenceSync;
extern PFNGLISSYNCPROC __glIsSync;
extern PFNGLDELETESYNCPROC __glDeleteSync;
extern PFNGLCLIENTWAITSYNCPROC __glClientWaitSync;
extern PFNGLWAITSYNCPROC __glWaitSync;
extern PFNGLGETINTEGER64VPROC __glGetInteger64v;
extern PFNGLGETSYNCIVPROC __glGetSynciv;
extern PFNGLGETINTEGER64I_VPROC __glGetInteger64i_v;
extern PFNGLGETBUFFERPARAMETERI64VPROC __glGetBufferParameteri64v;
extern PFNGLFRAMEBUFFERTEXTUREPROC __glFramebufferTexture;
extern PFNGLTEXIMAGE2DMULTISAMPLEPROC __glTexImage2DMultisample;
extern PFNGLTEXIMAGE3DMULTISAMPLEPROC __glTexImage3DMultisample;
extern PFNGLGETMULTISAMPLEFVPROC __glGetMultisamplefv;
extern PFNGLSAMPLEMASKIPROC __glSampleMaski;


// GL_VERSION_3_3
#define glBindFragDataLocationIndexed __glBindFragDataLocationIndexed
#define glGetFragDataIndex __glGetFragDataIndex
#define glGenSamplers __glGenSamplers
#define glDeleteSamplers __glDeleteSamplers
#define glIsSampler __glIsSampler
#define glBindSampler __glBindSampler
#define glSamplerParameteri __glSamplerParameteri
#define glSamplerParameteriv __glSamplerParameteriv
#define glSamplerParameterf __glSamplerParameterf
#define glSamplerParameterfv __glSamplerParameterfv
#define glSamplerParameterIiv __glSamplerParameterIiv
#define glSamplerParameterIuiv __glSamplerParameterIuiv
#define glGetSamplerParameteriv __glGetSamplerParameteriv
#define glGetSamplerParameterIiv __glGetSamplerParameterIiv
#define glGetSamplerParameterfv __glGetSamplerParameterfv
#define glGetSamplerParameterIuiv __glGetSamplerParameterIuiv
#define glQueryCounter __glQueryCounter
#define glGetQueryObjecti64v __glGetQueryObjecti64v
#define glGetQueryObjectui64v __glGetQueryObjectui64v
#define glVertexAttribDivisor __glVertexAttribDivisor
#define glVertexAttribP1ui __glVertexAttribP1ui
#define glVertexAttribP1uiv __glVertexAttribP1uiv
#define glVertexAttribP2ui __glVertexAttribP2ui
#define glVertexAttribP2uiv __glVertexAttribP2uiv
#define glVertexAttribP3ui __glVertexAttribP3ui
#define glVertexAttribP3uiv __glVertexAttribP3uiv
#define glVertexAttribP4ui __glVertexAttribP4ui
#define glVertexAttribP4uiv __glVertexAttribP4uiv
#define glVertexP2ui __glVertexP2ui
#define glVertexP2uiv __glVertexP2uiv
#define glVertexP3ui __glVertexP3ui
#define glVertexP3uiv __glVertexP3uiv
#define glVertexP4ui __glVertexP4ui
#define glVertexP4uiv __glVertexP4uiv
#define glTexCoordP1ui __glTexCoordP1ui
#define glTexCoordP1uiv __glTexCoordP1uiv
#define glTexCoordP2ui __glTexCoordP2ui
#define glTexCoordP2uiv __glTexCoordP2uiv
#define glTexCoordP3ui __glTexCoordP3ui
#define glTexCoordP3uiv __glTexCoordP3uiv
#define glTexCoordP4ui __glTexCoordP4ui
#define glTexCoordP4uiv __glTexCoordP4uiv
#define glMultiTexCoordP1ui __glMultiTexCoordP1ui
#define glMultiTexCoordP1uiv __glMultiTexCoordP1uiv
#define glMultiTexCoordP2ui __glMultiTexCoordP2ui
#define glMultiTexCoordP2uiv __glMultiTexCoordP2uiv
#define glMultiTexCoordP3ui __glMultiTexCoordP3ui
#define glMultiTexCoordP3uiv __glMultiTexCoordP3uiv
#define glMultiTexCoordP4ui __glMultiTexCoordP4ui
#define glMultiTexCoordP4uiv __glMultiTexCoordP4uiv
#define glNormalP3ui __glNormalP3ui
#define glNormalP3uiv __glNormalP3uiv
#define glColorP3ui __glColorP3ui
#define glColorP3uiv __glColorP3uiv
#define glColorP4ui __glColorP4ui
#define glColorP4uiv __glColorP4uiv
#define glSecondaryColorP3ui __glSecondaryColorP3ui
#define glSecondaryColorP3uiv __glSecondaryColorP3uiv

extern PFNGLBINDFRAGDATALOCATIONINDEXEDPROC __glBindFragDataLocationIndexed;
extern PFNGLGETFRAGDATAINDEXPROC __glGetFragDataIndex;
extern PFNGLGENSAMPLERSPROC __glGenSamplers;
extern PFNGLDELETESAMPLERSPROC __glDeleteSamplers;
extern PFNGLISSAMPLERPROC __glIsSampler;
extern PFNGLBINDSAMPLERPROC __glBindSampler;
extern PFNGLSAMPLERPARAMETERIPROC __glSamplerParameteri;
extern PFNGLSAMPLERPARAMETERIVPROC __glSamplerParameteriv;
extern PFNGLSAMPLERPARAMETERFPROC __glSamplerParameterf;
extern PFNGLSAMPLERPARAMETERFVPROC __glSamplerParameterfv;
extern PFNGLSAMPLERPARAMETERIIVPROC __glSamplerParameterIiv;
extern PFNGLSAMPLERPARAMETERIUIVPROC __glSamplerParameterIuiv;
extern PFNGLGETSAMPLERPARAMETERIVPROC __glGetSamplerParameteriv;
extern PFNGLGETSAMPLERPARAMETERIIVPROC __glGetSamplerParameterIiv;
extern PFNGLGETSAMPLERPARAMETERFVPROC __glGetSamplerParameterfv;
extern PFNGLGETSAMPLERPARAMETERIUIVPROC __glGetSamplerParameterIuiv;
extern PFNGLQUERYCOUNTERPROC __glQueryCounter;
extern PFNGLGETQUERYOBJECTI64VPROC __glGetQueryObjecti64v;
extern PFNGLGETQUERYOBJECTUI64VPROC __glGetQueryObjectui64v;
extern PFNGLVERTEXATTRIBDIVISORPROC __glVertexAttribDivisor;
extern PFNGLVERTEXATTRIBP1UIPROC __glVertexAttribP1ui;
extern PFNGLVERTEXATTRIBP1UIVPROC __glVertexAttribP1uiv;
extern PFNGLVERTEXATTRIBP2UIPROC __glVertexAttribP2ui;
extern PFNGLVERTEXATTRIBP2UIVPROC __glVertexAttribP2uiv;
extern PFNGLVERTEXATTRIBP3UIPROC __glVertexAttribP3ui;
extern PFNGLVERTEXATTRIBP3UIVPROC __glVertexAttribP3uiv;
extern PFNGLVERTEXATTRIBP4UIPROC __glVertexAttribP4ui;
extern PFNGLVERTEXATTRIBP4UIVPROC __glVertexAttribP4uiv;
extern PFNGLVERTEXP2UIPROC __glVertexP2ui;
extern PFNGLVERTEXP2UIVPROC __glVertexP2uiv;
extern PFNGLVERTEXP3UIPROC __glVertexP3ui;
extern PFNGLVERTEXP3UIVPROC __glVertexP3uiv;
extern PFNGLVERTEXP4UIPROC __glVertexP4ui;
extern PFNGLVERTEXP4UIVPROC __glVertexP4uiv;
extern PFNGLTEXCOORDP1UIPROC __glTexCoordP1ui;
extern PFNGLTEXCOORDP1UIVPROC __glTexCoordP1uiv;
extern PFNGLTEXCOORDP2UIPROC __glTexCoordP2ui;
extern PFNGLTEXCOORDP2UIVPROC __glTexCoordP2uiv;
extern PFNGLTEXCOORDP3UIPROC __glTexCoordP3ui;
extern PFNGLTEXCOORDP3UIVPROC __glTexCoordP3uiv;
extern PFNGLTEXCOORDP4UIPROC __glTexCoordP4ui;
extern PFNGLTEXCOORDP4UIVPROC __glTexCoordP4uiv;
extern PFNGLMULTITEXCOORDP1UIPROC __glMultiTexCoordP1ui;
extern PFNGLMULTITEXCOORDP1UIVPROC __glMultiTexCoordP1uiv;
extern PFNGLMULTITEXCOORDP2UIPROC __glMultiTexCoordP2ui;
extern PFNGLMULTITEXCOORDP2UIVPROC __glMultiTexCoordP2uiv;
extern PFNGLMULTITEXCOORDP3UIPROC __glMultiTexCoordP3ui;
extern PFNGLMULTITEXCOORDP3UIVPROC __glMultiTexCoordP3uiv;
extern PFNGLMULTITEXCOORDP4UIPROC __glMultiTexCoordP4ui;
extern PFNGLMULTITEXCOORDP4UIVPROC __glMultiTexCoordP4uiv;
extern PFNGLNORMALP3UIPROC __glNormalP3ui;
extern PFNGLNORMALP3UIVPROC __glNormalP3uiv;
extern PFNGLCOLORP3UIPROC __glColorP3ui;
extern PFNGLCOLORP3UIVPROC __glColorP3uiv;
extern PFNGLCOLORP4UIPROC __glColorP4ui;
extern PFNGLCOLORP4UIVPROC __glColorP4uiv;
extern PFNGLSECONDARYCOLORP3UIPROC __glSecondaryColorP3ui;
extern PFNGLSECONDARYCOLORP3UIVPROC __glSecondaryColorP3uiv;


// GL_VERSION_4_0
#define glMinSampleShading __glMinSampleShading
#define glBlendEquationi __glBlendEquationi
#define glBlendEquationSeparatei __glBlendEquationSeparatei
#define glBlendFunci __glBlendFunci
#define glBlendFuncSeparatei __glBlendFuncSeparatei
#define glDrawArraysIndirect __glDrawArraysIndirect
#define glDrawElementsIndirect __glDrawElementsIndirect
#define glUniform1d __glUniform1d
#define glUniform2d __glUniform2d
#define glUniform3d __glUniform3d
#define glUniform4d __glUniform4d
#define glUniform1dv __glUniform1dv
#define glUniform2dv __glUniform2dv
#define glUniform3dv __glUniform3dv
#define glUniform4dv __glUniform4dv
#define glUniformMatrix2dv __glUniformMatrix2dv
#define glUniformMatrix3dv __glUniformMatrix3dv
#define glUniformMatrix4dv __glUniformMatrix4dv
#define glUniformMatrix2x3dv __glUniformMatrix2x3dv
#define glUniformMatrix2x4dv __glUniformMatrix2x4dv
#define glUniformMatrix3x2dv __glUniformMatrix3x2dv
#define glUniformMatrix3x4dv __glUniformMatrix3x4dv
#define glUniformMatrix4x2dv __glUniformMatrix4x2dv
#define glUniformMatrix4x3dv __glUniformMatrix4x3dv
#define glGetUniformdv __glGetUniformdv
#define glGetSubroutineUniformLocation __glGetSubroutineUniformLocation
#define glGetSubroutineIndex __glGetSubroutineIndex
#define glGetActiveSubroutineUniformiv __glGetActiveSubroutineUniformiv
#define glGetActiveSubroutineUniformName __glGetActiveSubroutineUniformName
#define glGetActiveSubroutineName __glGetActiveSubroutineName
#define glUniformSubroutinesuiv __glUniformSubroutinesuiv
#define glGetUniformSubroutineuiv __glGetUniformSubroutineuiv
#define glGetProgramStageiv __glGetProgramStageiv
#define glPatchParameteri __glPatchParameteri
#define glPatchParameterfv __glPatchParameterfv
#define glBindTransformFeedback __glBindTransformFeedback
#define glDeleteTransformFeedbacks __glDeleteTransformFeedbacks
#define glGenTransformFeedbacks __glGenTransformFeedbacks
#define glIsTransformFeedback __glIsTransformFeedback
#define glPauseTransformFeedback __glPauseTransformFeedback
#define glResumeTransformFeedback __glResumeTransformFeedback
#define glDrawTransformFeedback __glDrawTransformFeedback
#define glDrawTransformFeedbackStream __glDrawTransformFeedbackStream
#define glBeginQueryIndexed __glBeginQueryIndexed
#define glEndQueryIndexed __glEndQueryIndexed
#define glGetQueryIndexediv __glGetQueryIndexediv

extern PFNGLMINSAMPLESHADINGPROC __glMinSampleShading;
extern PFNGLBLENDEQUATIONIPROC __glBlendEquationi;
extern PFNGLBLENDEQUATIONSEPARATEIPROC __glBlendEquationSeparatei;
extern PFNGLBLENDFUNCIPROC __glBlendFunci;
extern PFNGLBLENDFUNCSEPARATEIPROC __glBlendFuncSeparatei;
extern PFNGLDRAWARRAYSINDIRECTPROC __glDrawArraysIndirect;
extern PFNGLDRAWELEMENTSINDIRECTPROC __glDrawElementsIndirect;
extern PFNGLUNIFORM1DPROC __glUniform1d;
extern PFNGLUNIFORM2DPROC __glUniform2d;
extern PFNGLUNIFORM3DPROC __glUniform3d;
extern PFNGLUNIFORM4DPROC __glUniform4d;
extern PFNGLUNIFORM1DVPROC __glUniform1dv;
extern PFNGLUNIFORM2DVPROC __glUniform2dv;
extern PFNGLUNIFORM3DVPROC __glUniform3dv;
extern PFNGLUNIFORM4DVPROC __glUniform4dv;
extern PFNGLUNIFORMMATRIX2DVPROC __glUniformMatrix2dv;
extern PFNGLUNIFORMMATRIX3DVPROC __glUniformMatrix3dv;
extern PFNGLUNIFORMMATRIX4DVPROC __glUniformMatrix4dv;
extern PFNGLUNIFORMMATRIX2X3DVPROC __glUniformMatrix2x3dv;
extern PFNGLUNIFORMMATRIX2X4DVPROC __glUniformMatrix2x4dv;
extern PFNGLUNIFORMMATRIX3X2DVPROC __glUniformMatrix3x2dv;
extern PFNGLUNIFORMMATRIX3X4DVPROC __glUniformMatrix3x4dv;
extern PFNGLUNIFORMMATRIX4X2DVPROC __glUniformMatrix4x2dv;
extern PFNGLUNIFORMMATRIX4X3DVPROC __glUniformMatrix4x3dv;
extern PFNGLGETUNIFORMDVPROC __glGetUniformdv;
extern PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC __glGetSubroutineUniformLocation;
extern PFNGLGETSUBROUTINEINDEXPROC __glGetSubroutineIndex;
extern PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC __glGetActiveSubroutineUniformiv;
extern PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC __glGetActiveSubroutineUniformName;
extern PFNGLGETACTIVESUBROUTINENAMEPROC __glGetActiveSubroutineName;
extern PFNGLUNIFORMSUBROUTINESUIVPROC __glUniformSubroutinesuiv;
extern PFNGLGETUNIFORMSUBROUTINEUIVPROC __glGetUniformSubroutineuiv;
extern PFNGLGETPROGRAMSTAGEIVPROC __glGetProgramStageiv;
extern PFNGLPATCHPARAMETERIPROC __glPatchParameteri;
extern PFNGLPATCHPARAMETERFVPROC __glPatchParameterfv;
extern PFNGLBINDTRANSFORMFEEDBACKPROC __glBindTransformFeedback;
extern PFNGLDELETETRANSFORMFEEDBACKSPROC __glDeleteTransformFeedbacks;
extern PFNGLGENTRANSFORMFEEDBACKSPROC __glGenTransformFeedbacks;
extern PFNGLISTRANSFORMFEEDBACKPROC __glIsTransformFeedback;
extern PFNGLPAUSETRANSFORMFEEDBACKPROC __glPauseTransformFeedback;
extern PFNGLRESUMETRANSFORMFEEDBACKPROC __glResumeTransformFeedback;
extern PFNGLDRAWTRANSFORMFEEDBACKPROC __glDrawTransformFeedback;
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC __glDrawTransformFeedbackStream;
extern PFNGLBEGINQUERYINDEXEDPROC __glBeginQueryIndexed;
extern PFNGLENDQUERYINDEXEDPROC __glEndQueryIndexed;
extern PFNGLGETQUERYINDEXEDIVPROC __glGetQueryIndexediv;


// GL_VERSION_4_1
#define glReleaseShaderCompiler __glReleaseShaderCompiler
#define glShaderBinary __glShaderBinary
#define glGetShaderPrecisionFormat __glGetShaderPrecisionFormat
#define glDepthRangef __glDepthRangef
#define glClearDepthf __glClearDepthf
#define glGetProgramBinary __glGetProgramBinary
#define glProgramBinary __glProgramBinary
#define glProgramParameteri __glProgramParameteri
#define glUseProgramStages __glUseProgramStages
#define glActiveShaderProgram __glActiveShaderProgram
#define glCreateShaderProgramv __glCreateShaderProgramv
#define glBindProgramPipeline __glBindProgramPipeline
#define glDeleteProgramPipelines __glDeleteProgramPipelines
#define glGenProgramPipelines __glGenProgramPipelines
#define glIsProgramPipeline __glIsProgramPipeline
#define glGetProgramPipelineiv __glGetProgramPipelineiv
#define glProgramUniform1i __glProgramUniform1i
#define glProgramUniform1iv __glProgramUniform1iv
#define glProgramUniform1f __glProgramUniform1f
#define glProgramUniform1fv __glProgramUniform1fv
#define glProgramUniform1d __glProgramUniform1d
#define glProgramUniform1dv __glProgramUniform1dv
#define glProgramUniform1ui __glProgramUniform1ui
#define glProgramUniform1uiv __glProgramUniform1uiv
#define glProgramUniform2i __glProgramUniform2i
#define glProgramUniform2iv __glProgramUniform2iv
#define glProgramUniform2f __glProgramUniform2f
#define glProgramUniform2fv __glProgramUniform2fv
#define glProgramUniform2d __glProgramUniform2d
#define glProgramUniform2dv __glProgramUniform2dv
#define glProgramUniform2ui __glProgramUniform2ui
#define glProgramUniform2uiv __glProgramUniform2uiv
#define glProgramUniform3i __glProgramUniform3i
#define glProgramUniform3iv __glProgramUniform3iv
#define glProgramUniform3f __glProgramUniform3f
#define glProgramUniform3fv __glProgramUniform3fv
#define glProgramUniform3d __glProgramUniform3d
#define glProgramUniform3dv __glProgramUniform3dv
#define glProgramUniform3ui __glProgramUniform3ui
#define glProgramUniform3uiv __glProgramUniform3uiv
#define glProgramUniform4i __glProgramUniform4i
#define glProgramUniform4iv __glProgramUniform4iv
#define glProgramUniform4f __glProgramUniform4f
#define glProgramUniform4fv __glProgramUniform4fv
#define glProgramUniform4d __glProgramUniform4d
#define glProgramUniform4dv __glProgramUniform4dv
#define glProgramUniform4ui __glProgramUniform4ui
#define glProgramUniform4uiv __glProgramUniform4uiv
#define glProgramUniformMatrix2fv __glProgramUniformMatrix2fv
#define glProgramUniformMatrix3fv __glProgramUniformMatrix3fv
#define glProgramUniformMatrix4fv __glProgramUniformMatrix4fv
#define glProgramUniformMatrix2dv __glProgramUniformMatrix2dv
#define glProgramUniformMatrix3dv __glProgramUniformMatrix3dv
#define glProgramUniformMatrix4dv __glProgramUniformMatrix4dv
#define glProgramUniformMatrix2x3fv __glProgramUniformMatrix2x3fv
#define glProgramUniformMatrix3x2fv __glProgramUniformMatrix3x2fv
#define glProgramUniformMatrix2x4fv __glProgramUniformMatrix2x4fv
#define glProgramUniformMatrix4x2fv __glProgramUniformMatrix4x2fv
#define glProgramUniformMatrix3x4fv __glProgramUniformMatrix3x4fv
#define glProgramUniformMatrix4x3fv __glProgramUniformMatrix4x3fv
#define glProgramUniformMatrix2x3dv __glProgramUniformMatrix2x3dv
#define glProgramUniformMatrix3x2dv __glProgramUniformMatrix3x2dv
#define glProgramUniformMatrix2x4dv __glProgramUniformMatrix2x4dv
#define glProgramUniformMatrix4x2dv __glProgramUniformMatrix4x2dv
#define glProgramUniformMatrix3x4dv __glProgramUniformMatrix3x4dv
#define glProgramUniformMatrix4x3dv __glProgramUniformMatrix4x3dv
#define glValidateProgramPipeline __glValidateProgramPipeline
#define glGetProgramPipelineInfoLog __glGetProgramPipelineInfoLog
#define glVertexAttribL1d __glVertexAttribL1d
#define glVertexAttribL2d __glVertexAttribL2d
#define glVertexAttribL3d __glVertexAttribL3d
#define glVertexAttribL4d __glVertexAttribL4d
#define glVertexAttribL1dv __glVertexAttribL1dv
#define glVertexAttribL2dv __glVertexAttribL2dv
#define glVertexAttribL3dv __glVertexAttribL3dv
#define glVertexAttribL4dv __glVertexAttribL4dv
#define glVertexAttribLPointer __glVertexAttribLPointer
#define glGetVertexAttribLdv __glGetVertexAttribLdv
#define glViewportArrayv __glViewportArrayv
#define glViewportIndexedf __glViewportIndexedf
#define glViewportIndexedfv __glViewportIndexedfv
#define glScissorArrayv __glScissorArrayv
#define glScissorIndexed __glScissorIndexed
#define glScissorIndexedv __glScissorIndexedv
#define glDepthRangeArrayv __glDepthRangeArrayv
#define glDepthRangeIndexed __glDepthRangeIndexed
#define glGetFloati_v __glGetFloati_v
#define glGetDoublei_v __glGetDoublei_v

extern PFNGLRELEASESHADERCOMPILERPROC __glReleaseShaderCompiler;
extern PFNGLSHADERBINARYPROC __glShaderBinary;
extern PFNGLGETSHADERPRECISIONFORMATPROC __glGetShaderPrecisionFormat;
extern PFNGLDEPTHRANGEFPROC __glDepthRangef;
extern PFNGLCLEARDEPTHFPROC __glClearDepthf;
extern PFNGLGETPROGRAMBINARYPROC __glGetProgramBinary;
extern PFNGLPROGRAMBINARYPROC __glProgramBinary;
extern PFNGLPROGRAMPARAMETERIPROC __glProgramParameteri;
extern PFNGLUSEPROGRAMSTAGESPROC __glUseProgramStages;
extern PFNGLACTIVESHADERPROGRAMPROC __glActiveShaderProgram;
extern PFNGLCREATESHADERPROGRAMVPROC __glCreateShaderProgramv;
extern PFNGLBINDPROGRAMPIPELINEPROC __glBindProgramPipeline;
extern PFNGLDELETEPROGRAMPIPELINESPROC __glDeleteProgramPipelines;
extern PFNGLGENPROGRAMPIPELINESPROC __glGenProgramPipelines;
extern PFNGLISPROGRAMPIPELINEPROC __glIsProgramPipeline;
extern PFNGLGETPROGRAMPIPELINEIVPROC __glGetProgramPipelineiv;
extern PFNGLPROGRAMUNIFORM1IPROC __glProgramUniform1i;
extern PFNGLPROGRAMUNIFORM1IVPROC __glProgramUniform1iv;
extern PFNGLPROGRAMUNIFORM1FPROC __glProgramUniform1f;
extern PFNGLPROGRAMUNIFORM1FVPROC __glProgramUniform1fv;
extern PFNGLPROGRAMUNIFORM1DPROC __glProgramUniform1d;
extern PFNGLPROGRAMUNIFORM1DVPROC __glProgramUniform1dv;
extern PFNGLPROGRAMUNIFORM1UIPROC __glProgramUniform1ui;
extern PFNGLPROGRAMUNIFORM1UIVPROC __glProgramUniform1uiv;
extern PFNGLPROGRAMUNIFORM2IPROC __glProgramUniform2i;
extern PFNGLPROGRAMUNIFORM2IVPROC __glProgramUniform2iv;
extern PFNGLPROGRAMUNIFORM2FPROC __glProgramUniform2f;
extern PFNGLPROGRAMUNIFORM2FVPROC __glProgramUniform2fv;
extern PFNGLPROGRAMUNIFORM2DPROC __glProgramUniform2d;
extern PFNGLPROGRAMUNIFORM2DVPROC __glProgramUniform2dv;
extern PFNGLPROGRAMUNIFORM2UIPROC __glProgramUniform2ui;
extern PFNGLPROGRAMUNIFORM2UIVPROC __glProgramUniform2uiv;
extern PFNGLPROGRAMUNIFORM3IPROC __glProgramUniform3i;
extern PFNGLPROGRAMUNIFORM3IVPROC __glProgramUniform3iv;
extern PFNGLPROGRAMUNIFORM3FPROC __glProgramUniform3f;
extern PFNGLPROGRAMUNIFORM3FVPROC __glProgramUniform3fv;
extern PFNGLPROGRAMUNIFORM3DPROC __glProgramUniform3d;
extern PFNGLPROGRAMUNIFORM3DVPROC __glProgramUniform3dv;
extern PFNGLPROGRAMUNIFORM3UIPROC __glProgramUniform3ui;
extern PFNGLPROGRAMUNIFORM3UIVPROC __glProgramUniform3uiv;
extern PFNGLPROGRAMUNIFORM4IPROC __glProgramUniform4i;
extern PFNGLPROGRAMUNIFORM4IVPROC __glProgramUniform4iv;
extern PFNGLPROGRAMUNIFORM4FPROC __glProgramUniform4f;
extern PFNGLPROGRAMUNIFORM4FVPROC __glProgramUniform4fv;
extern PFNGLPROGRAMUNIFORM4DPROC __glProgramUniform4d;
extern PFNGLPROGRAMUNIFORM4DVPROC __glProgramUniform4dv;
extern PFNGLPROGRAMUNIFORM4UIPROC __glProgramUniform4ui;
extern PFNGLPROGRAMUNIFORM4UIVPROC __glProgramUniform4uiv;
extern PFNGLPROGRAMUNIFORMMATRIX2FVPROC __glProgramUniformMatrix2fv;
extern PFNGLPROGRAMUNIFORMMATRIX3FVPROC __glProgramUniformMatrix3fv;
extern PFNGLPROGRAMUNIFORMMATRIX4FVPROC __glProgramUniformMatrix4fv;
extern PFNGLPROGRAMUNIFORMMATRIX2DVPROC __glProgramUniformMatrix2dv;
extern PFNGLPROGRAMUNIFORMMATRIX3DVPROC __glProgramUniformMatrix3dv;
extern PFNGLPROGRAMUNIFORMMATRIX4DVPROC __glProgramUniformMatrix4dv;
extern PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC __glProgramUniformMatrix2x3fv;
extern PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC __glProgramUniformMatrix3x2fv;
extern PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC __glProgramUniformMatrix2x4fv;
extern PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC __glProgramUniformMatrix4x2fv;
extern PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC __glProgramUniformMatrix3x4fv;
extern PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC __glProgramUniformMatrix4x3fv;
extern PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC __glProgramUniformMatrix2x3dv;
extern PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC __glProgramUniformMatrix3x2dv;
extern PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC __glProgramUniformMatrix2x4dv;
extern PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC __glProgramUniformMatrix4x2dv;
extern PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC __glProgramUniformMatrix3x4dv;
extern PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC __glProgramUniformMatrix4x3dv;
extern PFNGLVALIDATEPROGRAMPIPELINEPROC __glValidateProgramPipeline;
extern PFNGLGETPROGRAMPIPELINEINFOLOGPROC __glGetProgramPipelineInfoLog;
extern PFNGLVERTEXATTRIBL1DPROC __glVertexAttribL1d;
extern PFNGLVERTEXATTRIBL2DPROC __glVertexAttribL2d;
extern PFNGLVERTEXATTRIBL3DPROC __glVertexAttribL3d;
extern PFNGLVERTEXATTRIBL4DPROC __glVertexAttribL4d;
extern PFNGLVERTEXATTRIBL1DVPROC __glVertexAttribL1dv;
extern PFNGLVERTEXATTRIBL2DVPROC __glVertexAttribL2dv;
extern PFNGLVERTEXATTRIBL3DVPROC __glVertexAttribL3dv;
extern PFNGLVERTEXATTRIBL4DVPROC __glVertexAttribL4dv;
extern PFNGLVERTEXATTRIBLPOINTERPROC __glVertexAttribLPointer;
extern PFNGLGETVERTEXATTRIBLDVPROC __glGetVertexAttribLdv;
extern PFNGLVIEWPORTARRAYVPROC __glViewportArrayv;
extern PFNGLVIEWPORTINDEXEDFPROC __glViewportIndexedf;
extern PFNGLVIEWPORTINDEXEDFVPROC __glViewportIndexedfv;
extern PFNGLSCISSORARRAYVPROC __glScissorArrayv;
extern PFNGLSCISSORINDEXEDPROC __glScissorIndexed;
extern PFNGLSCISSORINDEXEDVPROC __glScissorIndexedv;
extern PFNGLDEPTHRANGEARRAYVPROC __glDepthRangeArrayv;
extern PFNGLDEPTHRANGEINDEXEDPROC __glDepthRangeIndexed;
extern PFNGLGETFLOATI_VPROC __glGetFloati_v;
extern PFNGLGETDOUBLEI_VPROC __glGetDoublei_v;


// GL_VERSION_4_2
#define glDrawArraysInstancedBaseInstance __glDrawArraysInstancedBaseInstance
#define glDrawElementsInstancedBaseInstance __glDrawElementsInstancedBaseInstance
#define glDrawElementsInstancedBaseVertexBaseInstance __glDrawElementsInstancedBaseVertexBaseInstance
#define glGetInternalformativ __glGetInternalformativ
#define glGetActiveAtomicCounterBufferiv __glGetActiveAtomicCounterBufferiv
#define glBindImageTexture __glBindImageTexture
#define glMemoryBarrier __glMemoryBarrier
#define glTexStorage1D __glTexStorage1D
#define glTexStorage2D __glTexStorage2D
#define glTexStorage3D __glTexStorage3D
#define glDrawTransformFeedbackInstanced __glDrawTransformFeedbackInstanced
#define glDrawTransformFeedbackStreamInstanced __glDrawTransformFeedbackStreamInstanced

extern PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC __glDrawArraysInstancedBaseInstance;
extern PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC __glDrawElementsInstancedBaseInstance;
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC __glDrawElementsInstancedBaseVertexBaseInstance;
extern PFNGLGETINTERNALFORMATIVPROC __glGetInternalformativ;
extern PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC __glGetActiveAtomicCounterBufferiv;
extern PFNGLBINDIMAGETEXTUREPROC __glBindImageTexture;
extern PFNGLMEMORYBARRIERPROC __glMemoryBarrier;
extern PFNGLTEXSTORAGE1DPROC __glTexStorage1D;
extern PFNGLTEXSTORAGE2DPROC __glTexStorage2D;
extern PFNGLTEXSTORAGE3DPROC __glTexStorage3D;
extern PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC __glDrawTransformFeedbackInstanced;
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC __glDrawTransformFeedbackStreamInstanced;


// GL_VERSION_4_3
#define glClearBufferData __glClearBufferData
#define glClearBufferSubData __glClearBufferSubData
#define glDispatchCompute __glDispatchCompute
#define glDispatchComputeIndirect __glDispatchComputeIndirect
#define glCopyImageSubData __glCopyImageSubData
#define glFramebufferParameteri __glFramebufferParameteri
#define glGetFramebufferParameteriv __glGetFramebufferParameteriv
#define glGetInternalformati64v __glGetInternalformati64v
#define glInvalidateTexSubImage __glInvalidateTexSubImage
#define glInvalidateTexImage __glInvalidateTexImage
#define glInvalidateBufferSubData __glInvalidateBufferSubData
#define glInvalidateBufferData __glInvalidateBufferData
#define glInvalidateFramebuffer __glInvalidateFramebuffer
#define glInvalidateSubFramebuffer __glInvalidateSubFramebuffer
#define glMultiDrawArraysIndirect __glMultiDrawArraysIndirect
#define glMultiDrawElementsIndirect __glMultiDrawElementsIndirect
#define glGetProgramInterfaceiv __glGetProgramInterfaceiv
#define glGetProgramResourceIndex __glGetProgramResourceIndex
#define glGetProgramResourceName __glGetProgramResourceName
#define glGetProgramResourceiv __glGetProgramResourceiv
#define glGetProgramResourceLocation __glGetProgramResourceLocation
#define glGetProgramResourceLocationIndex __glGetProgramResourceLocationIndex
#define glShaderStorageBlockBinding __glShaderStorageBlockBinding
#define glTexBufferRange __glTexBufferRange
#define glTexStorage2DMultisample __glTexStorage2DMultisample
#define glTexStorage3DMultisample __glTexStorage3DMultisample
#define glTextureView __glTextureView
#define glBindVertexBuffer __glBindVertexBuffer
#define glVertexAttribFormat __glVertexAttribFormat
#define glVertexAttribIFormat __glVertexAttribIFormat
#define glVertexAttribLFormat __glVertexAttribLFormat
#define glVertexAttribBinding __glVertexAttribBinding
#define glVertexBindingDivisor __glVertexBindingDivisor
#define glDebugMessageControl __glDebugMessageControl
#define glDebugMessageInsert __glDebugMessageInsert
#define glDebugMessageCallback __glDebugMessageCallback
#define glGetDebugMessageLog __glGetDebugMessageLog
#define glPushDebugGroup __glPushDebugGroup
#define glPopDebugGroup __glPopDebugGroup
#define glObjectLabel __glObjectLabel
#define glGetObjectLabel __glGetObjectLabel
#define glObjectPtrLabel __glObjectPtrLabel
#define glGetObjectPtrLabel __glGetObjectPtrLabel

extern PFNGLCLEARBUFFERDATAPROC __glClearBufferData;
extern PFNGLCLEARBUFFERSUBDATAPROC __glClearBufferSubData;
extern PFNGLDISPATCHCOMPUTEPROC __glDispatchCompute;
extern PFNGLDISPATCHCOMPUTEINDIRECTPROC __glDispatchComputeIndirect;
extern PFNGLCOPYIMAGESUBDATAPROC __glCopyImageSubData;
extern PFNGLFRAMEBUFFERPARAMETERIPROC __glFramebufferParameteri;
extern PFNGLGETFRAMEBUFFERPARAMETERIVPROC __glGetFramebufferParameteriv;
extern PFNGLGETINTERNALFORMATI64VPROC __glGetInternalformati64v;
extern PFNGLINVALIDATETEXSUBIMAGEPROC __glInvalidateTexSubImage;
extern PFNGLINVALIDATETEXIMAGEPROC __glInvalidateTexImage;
extern PFNGLINVALIDATEBUFFERSUBDATAPROC __glInvalidateBufferSubData;
extern PFNGLINVALIDATEBUFFERDATAPROC __glInvalidateBufferData;
extern PFNGLINVALIDATEFRAMEBUFFERPROC __glInvalidateFramebuffer;
extern PFNGLINVALIDATESUBFRAMEBUFFERPROC __glInvalidateSubFramebuffer;
extern PFNGLMULTIDRAWARRAYSINDIRECTPROC __glMultiDrawArraysIndirect;
extern PFNGLMULTIDRAWELEMENTSINDIRECTPROC __glMultiDrawElementsIndirect;
extern PFNGLGETPROGRAMINTERFACEIVPROC __glGetProgramInterfaceiv;
extern PFNGLGETPROGRAMRESOURCEINDEXPROC __glGetProgramResourceIndex;
extern PFNGLGETPROGRAMRESOURCENAMEPROC __glGetProgramResourceName;
extern PFNGLGETPROGRAMRESOURCEIVPROC __glGetProgramResourceiv;
extern PFNGLGETPROGRAMRESOURCELOCATIONPROC __glGetProgramResourceLocation;
extern PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC __glGetProgramResourceLocationIndex;
extern PFNGLSHADERSTORAGEBLOCKBINDINGPROC __glShaderStorageBlockBinding;
extern PFNGLTEXBUFFERRANGEPROC __glTexBufferRange;
extern PFNGLTEXSTORAGE2DMULTISAMPLEPROC __glTexStorage2DMultisample;
extern PFNGLTEXSTORAGE3DMULTISAMPLEPROC __glTexStorage3DMultisample;
extern PFNGLTEXTUREVIEWPROC __glTextureView;
extern PFNGLBINDVERTEXBUFFERPROC __glBindVertexBuffer;
extern PFNGLVERTEXATTRIBFORMATPROC __glVertexAttribFormat;
extern PFNGLVERTEXATTRIBIFORMATPROC __glVertexAttribIFormat;
extern PFNGLVERTEXATTRIBLFORMATPROC __glVertexAttribLFormat;
extern PFNGLVERTEXATTRIBBINDINGPROC __glVertexAttribBinding;
extern PFNGLVERTEXBINDINGDIVISORPROC __glVertexBindingDivisor;
extern PFNGLDEBUGMESSAGECONTROLPROC __glDebugMessageControl;
extern PFNGLDEBUGMESSAGEINSERTPROC __glDebugMessageInsert;
extern PFNGLDEBUGMESSAGECALLBACKPROC __glDebugMessageCallback;
extern PFNGLGETDEBUGMESSAGELOGPROC __glGetDebugMessageLog;
extern PFNGLPUSHDEBUGGROUPPROC __glPushDebugGroup;
extern PFNGLPOPDEBUGGROUPPROC __glPopDebugGroup;
extern PFNGLOBJECTLABELPROC __glObjectLabel;
extern PFNGLGETOBJECTLABELPROC __glGetObjectLabel;
extern PFNGLOBJECTPTRLABELPROC __glObjectPtrLabel;
extern PFNGLGETOBJECTPTRLABELPROC __glGetObjectPtrLabel;


// GL_VERSION_4_4
#define glBufferStorage __glBufferStorage
#define glClearTexImage __glClearTexImage
#define glClearTexSubImage __glClearTexSubImage
#define glBindBuffersBase __glBindBuffersBase
#define glBindBuffersRange __glBindBuffersRange
#define glBindTextures __glBindTextures
#define glBindSamplers __glBindSamplers
#define glBindImageTextures __glBindImageTextures
#define glBindVertexBuffers __glBindVertexBuffers

extern PFNGLBUFFERSTORAGEPROC __glBufferStorage;
extern PFNGLCLEARTEXIMAGEPROC __glClearTexImage;
extern PFNGLCLEARTEXSUBIMAGEPROC __glClearTexSubImage;
extern PFNGLBINDBUFFERSBASEPROC __glBindBuffersBase;
extern PFNGLBINDBUFFERSRANGEPROC __glBindBuffersRange;
extern PFNGLBINDTEXTURESPROC __glBindTextures;
extern PFNGLBINDSAMPLERSPROC __glBindSamplers;
extern PFNGLBINDIMAGETEXTURESPROC __glBindImageTextures;
extern PFNGLBINDVERTEXBUFFERSPROC __glBindVertexBuffers;


// GL_VERSION_4_5
#define glClipControl __glClipControl
#define glCreateTransformFeedbacks __glCreateTransformFeedbacks
#define glTransformFeedbackBufferBase __glTransformFeedbackBufferBase
#define glTransformFeedbackBufferRange __glTransformFeedbackBufferRange
#define glGetTransformFeedbackiv __glGetTransformFeedbackiv
#define glGetTransformFeedbacki_v __glGetTransformFeedbacki_v
#define glGetTransformFeedbacki64_v __glGetTransformFeedbacki64_v
#define glCreateBuffers __glCreateBuffers
#define glNamedBufferStorage __glNamedBufferStorage
#define glNamedBufferData __glNamedBufferData
#define glNamedBufferSubData __glNamedBufferSubData
#define glCopyNamedBufferSubData __glCopyNamedBufferSubData
#define glClearNamedBufferData __glClearNamedBufferData
#define glClearNamedBufferSubData __glClearNamedBufferSubData
#define glMapNamedBuffer __glMapNamedBuffer
#define glMapNamedBufferRange __glMapNamedBufferRange
#define glUnmapNamedBuffer __glUnmapNamedBuffer
#define glFlushMappedNamedBufferRange __glFlushMappedNamedBufferRange
#define glGetNamedBufferParameteriv __glGetNamedBufferParameteriv
#define glGetNamedBufferParameteri64v __glGetNamedBufferParameteri64v
#define glGetNamedBufferPointerv __glGetNamedBufferPointerv
#define glGetNamedBufferSubData __glGetNamedBufferSubData
#define glCreateFramebuffers __glCreateFramebuffers
#define glNamedFramebufferRenderbuffer __glNamedFramebufferRenderbuffer
#define glNamedFramebufferParameteri __glNamedFramebufferParameteri
#define glNamedFramebufferTexture __glNamedFramebufferTexture
#define glNamedFramebufferTextureLayer __glNamedFramebufferTextureLayer
#define glNamedFramebufferDrawBuffer __glNamedFramebufferDrawBuffer
#define glNamedFramebufferDrawBuffers __glNamedFramebufferDrawBuffers
#define glNamedFramebufferReadBuffer __glNamedFramebufferReadBuffer
#define glInvalidateNamedFramebufferData __glInvalidateNamedFramebufferData
#define glInvalidateNamedFramebufferSubData __glInvalidateNamedFramebufferSubData
#define glClearNamedFramebufferiv __glClearNamedFramebufferiv
#define glClearNamedFramebufferuiv __glClearNamedFramebufferuiv
#define glClearNamedFramebufferfv __glClearNamedFramebufferfv
#define glClearNamedFramebufferfi __glClearNamedFramebufferfi
#define glBlitNamedFramebuffer __glBlitNamedFramebuffer
#define glCheckNamedFramebufferStatus __glCheckNamedFramebufferStatus
#define glGetNamedFramebufferParameteriv __glGetNamedFramebufferParameteriv
#define glGetNamedFramebufferAttachmentParameteriv __glGetNamedFramebufferAttachmentParameteriv
#define glCreateRenderbuffers __glCreateRenderbuffers
#define glNamedRenderbufferStorage __glNamedRenderbufferStorage
#define glNamedRenderbufferStorageMultisample __glNamedRenderbufferStorageMultisample
#define glGetNamedRenderbufferParameteriv __glGetNamedRenderbufferParameteriv
#define glCreateTextures __glCreateTextures
#define glTextureBuffer __glTextureBuffer
#define glTextureBufferRange __glTextureBufferRange
#define glTextureStorage1D __glTextureStorage1D
#define glTextureStorage2D __glTextureStorage2D
#define glTextureStorage3D __glTextureStorage3D
#define glTextureStorage2DMultisample __glTextureStorage2DMultisample
#define glTextureStorage3DMultisample __glTextureStorage3DMultisample
#define glTextureSubImage1D __glTextureSubImage1D
#define glTextureSubImage2D __glTextureSubImage2D
#define glTextureSubImage3D __glTextureSubImage3D
#define glCompressedTextureSubImage1D __glCompressedTextureSubImage1D
#define glCompressedTextureSubImage2D __glCompressedTextureSubImage2D
#define glCompressedTextureSubImage3D __glCompressedTextureSubImage3D
#define glCopyTextureSubImage1D __glCopyTextureSubImage1D
#define glCopyTextureSubImage2D __glCopyTextureSubImage2D
#define glCopyTextureSubImage3D __glCopyTextureSubImage3D
#define glTextureParameterf __glTextureParameterf
#define glTextureParameterfv __glTextureParameterfv
#define glTextureParameteri __glTextureParameteri
#define glTextureParameterIiv __glTextureParameterIiv
#define glTextureParameterIuiv __glTextureParameterIuiv
#define glTextureParameteriv __glTextureParameteriv
#define glGenerateTextureMipmap __glGenerateTextureMipmap
#define glBindTextureUnit __glBindTextureUnit
#define glGetTextureImage __glGetTextureImage
#define glGetCompressedTextureImage __glGetCompressedTextureImage
#define glGetTextureLevelParameterfv __glGetTextureLevelParameterfv
#define glGetTextureLevelParameteriv __glGetTextureLevelParameteriv
#define glGetTextureParameterfv __glGetTextureParameterfv
#define glGetTextureParameterIiv __glGetTextureParameterIiv
#define glGetTextureParameterIuiv __glGetTextureParameterIuiv
#define glGetTextureParameteriv __glGetTextureParameteriv
#define glCreateVertexArrays __glCreateVertexArrays
#define glDisableVertexArrayAttrib __glDisableVertexArrayAttrib
#define glEnableVertexArrayAttrib __glEnableVertexArrayAttrib
#define glVertexArrayElementBuffer __glVertexArrayElementBuffer
#define glVertexArrayVertexBuffer __glVertexArrayVertexBuffer
#define glVertexArrayVertexBuffers __glVertexArrayVertexBuffers
#define glVertexArrayAttribBinding __glVertexArrayAttribBinding
#define glVertexArrayAttribFormat __glVertexArrayAttribFormat
#define glVertexArrayAttribIFormat __glVertexArrayAttribIFormat
#define glVertexArrayAttribLFormat __glVertexArrayAttribLFormat
#define glVertexArrayBindingDivisor __glVertexArrayBindingDivisor
#define glGetVertexArrayiv __glGetVertexArrayiv
#define glGetVertexArrayIndexediv __glGetVertexArrayIndexediv
#define glGetVertexArrayIndexed64iv __glGetVertexArrayIndexed64iv
#define glCreateSamplers __glCreateSamplers
#define glCreateProgramPipelines __glCreateProgramPipelines
#define glCreateQueries __glCreateQueries
#define glGetQueryBufferObjecti64v __glGetQueryBufferObjecti64v
#define glGetQueryBufferObjectiv __glGetQueryBufferObjectiv
#define glGetQueryBufferObjectui64v __glGetQueryBufferObjectui64v
#define glGetQueryBufferObjectuiv __glGetQueryBufferObjectuiv
#define glMemoryBarrierByRegion __glMemoryBarrierByRegion
#define glGetTextureSubImage __glGetTextureSubImage
#define glGetCompressedTextureSubImage __glGetCompressedTextureSubImage
#define glGetGraphicsResetStatus __glGetGraphicsResetStatus
#define glGetnCompressedTexImage __glGetnCompressedTexImage
#define glGetnTexImage __glGetnTexImage
#define glGetnUniformdv __glGetnUniformdv
#define glGetnUniformfv __glGetnUniformfv
#define glGetnUniformiv __glGetnUniformiv
#define glGetnUniformuiv __glGetnUniformuiv
#define glReadnPixels __glReadnPixels
#define glGetnMapdv __glGetnMapdv
#define glGetnMapfv __glGetnMapfv
#define glGetnMapiv __glGetnMapiv
#define glGetnPixelMapfv __glGetnPixelMapfv
#define glGetnPixelMapuiv __glGetnPixelMapuiv
#define glGetnPixelMapusv __glGetnPixelMapusv
#define glGetnPolygonStipple __glGetnPolygonStipple
#define glGetnColorTable __glGetnColorTable
#define glGetnConvolutionFilter __glGetnConvolutionFilter
#define glGetnSeparableFilter __glGetnSeparableFilter
#define glGetnHistogram __glGetnHistogram
#define glGetnMinmax __glGetnMinmax
#define glTextureBarrier __glTextureBarrier

extern PFNGLCLIPCONTROLPROC __glClipControl;
extern PFNGLCREATETRANSFORMFEEDBACKSPROC __glCreateTransformFeedbacks;
extern PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC __glTransformFeedbackBufferBase;
extern PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC __glTransformFeedbackBufferRange;
extern PFNGLGETTRANSFORMFEEDBACKIVPROC __glGetTransformFeedbackiv;
extern PFNGLGETTRANSFORMFEEDBACKI_VPROC __glGetTransformFeedbacki_v;
extern PFNGLGETTRANSFORMFEEDBACKI64_VPROC __glGetTransformFeedbacki64_v;
extern PFNGLCREATEBUFFERSPROC __glCreateBuffers;
extern PFNGLNAMEDBUFFERSTORAGEPROC __glNamedBufferStorage;
extern PFNGLNAMEDBUFFERDATAPROC __glNamedBufferData;
extern PFNGLNAMEDBUFFERSUBDATAPROC __glNamedBufferSubData;
extern PFNGLCOPYNAMEDBUFFERSUBDATAPROC __glCopyNamedBufferSubData;
extern PFNGLCLEARNAMEDBUFFERDATAPROC __glClearNamedBufferData;
extern PFNGLCLEARNAMEDBUFFERSUBDATAPROC __glClearNamedBufferSubData;
extern PFNGLMAPNAMEDBUFFERPROC __glMapNamedBuffer;
extern PFNGLMAPNAMEDBUFFERRANGEPROC __glMapNamedBufferRange;
extern PFNGLUNMAPNAMEDBUFFERPROC __glUnmapNamedBuffer;
extern PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC __glFlushMappedNamedBufferRange;
extern PFNGLGETNAMEDBUFFERPARAMETERIVPROC __glGetNamedBufferParameteriv;
extern PFNGLGETNAMEDBUFFERPARAMETERI64VPROC __glGetNamedBufferParameteri64v;
extern PFNGLGETNAMEDBUFFERPOINTERVPROC __glGetNamedBufferPointerv;
extern PFNGLGETNAMEDBUFFERSUBDATAPROC __glGetNamedBufferSubData;
extern PFNGLCREATEFRAMEBUFFERSPROC __glCreateFramebuffers;
extern PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC __glNamedFramebufferRenderbuffer;
extern PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC __glNamedFramebufferParameteri;
extern PFNGLNAMEDFRAMEBUFFERTEXTUREPROC __glNamedFramebufferTexture;
extern PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC __glNamedFramebufferTextureLayer;
extern PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC __glNamedFramebufferDrawBuffer;
extern PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC __glNamedFramebufferDrawBuffers;
extern PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC __glNamedFramebufferReadBuffer;
extern PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC __glInvalidateNamedFramebufferData;
extern PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC __glInvalidateNamedFramebufferSubData;
extern PFNGLCLEARNAMEDFRAMEBUFFERIVPROC __glClearNamedFramebufferiv;
extern PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC __glClearNamedFramebufferuiv;
extern PFNGLCLEARNAMEDFRAMEBUFFERFVPROC __glClearNamedFramebufferfv;
extern PFNGLCLEARNAMEDFRAMEBUFFERFIPROC __glClearNamedFramebufferfi;
extern PFNGLBLITNAMEDFRAMEBUFFERPROC __glBlitNamedFramebuffer;
extern PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC __glCheckNamedFramebufferStatus;
extern PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC __glGetNamedFramebufferParameteriv;
extern PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC __glGetNamedFramebufferAttachmentParameteriv;
extern PFNGLCREATERENDERBUFFERSPROC __glCreateRenderbuffers;
extern PFNGLNAMEDRENDERBUFFERSTORAGEPROC __glNamedRenderbufferStorage;
extern PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC __glNamedRenderbufferStorageMultisample;
extern PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC __glGetNamedRenderbufferParameteriv;
extern PFNGLCREATETEXTURESPROC __glCreateTextures;
extern PFNGLTEXTUREBUFFERPROC __glTextureBuffer;
extern PFNGLTEXTUREBUFFERRANGEPROC __glTextureBufferRange;
extern PFNGLTEXTURESTORAGE1DPROC __glTextureStorage1D;
extern PFNGLTEXTURESTORAGE2DPROC __glTextureStorage2D;
extern PFNGLTEXTURESTORAGE3DPROC __glTextureStorage3D;
extern PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC __glTextureStorage2DMultisample;
extern PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC __glTextureStorage3DMultisample;
extern PFNGLTEXTURESUBIMAGE1DPROC __glTextureSubImage1D;
extern PFNGLTEXTURESUBIMAGE2DPROC __glTextureSubImage2D;
extern PFNGLTEXTURESUBIMAGE3DPROC __glTextureSubImage3D;
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC __glCompressedTextureSubImage1D;
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC __glCompressedTextureSubImage2D;
extern PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC __glCompressedTextureSubImage3D;
extern PFNGLCOPYTEXTURESUBIMAGE1DPROC __glCopyTextureSubImage1D;
extern PFNGLCOPYTEXTURESUBIMAGE2DPROC __glCopyTextureSubImage2D;
extern PFNGLCOPYTEXTURESUBIMAGE3DPROC __glCopyTextureSubImage3D;
extern PFNGLTEXTUREPARAMETERFPROC __glTextureParameterf;
extern PFNGLTEXTUREPARAMETERFVPROC __glTextureParameterfv;
extern PFNGLTEXTUREPARAMETERIPROC __glTextureParameteri;
extern PFNGLTEXTUREPARAMETERIIVPROC __glTextureParameterIiv;
extern PFNGLTEXTUREPARAMETERIUIVPROC __glTextureParameterIuiv;
extern PFNGLTEXTUREPARAMETERIVPROC __glTextureParameteriv;
extern PFNGLGENERATETEXTUREMIPMAPPROC __glGenerateTextureMipmap;
extern PFNGLBINDTEXTUREUNITPROC __glBindTextureUnit;
extern PFNGLGETTEXTUREIMAGEPROC __glGetTextureImage;
extern PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC __glGetCompressedTextureImage;
extern PFNGLGETTEXTURELEVELPARAMETERFVPROC __glGetTextureLevelParameterfv;
extern PFNGLGETTEXTURELEVELPARAMETERIVPROC __glGetTextureLevelParameteriv;
extern PFNGLGETTEXTUREPARAMETERFVPROC __glGetTextureParameterfv;
extern PFNGLGETTEXTUREPARAMETERIIVPROC __glGetTextureParameterIiv;
extern PFNGLGETTEXTUREPARAMETERIUIVPROC __glGetTextureParameterIuiv;
extern PFNGLGETTEXTUREPARAMETERIVPROC __glGetTextureParameteriv;
extern PFNGLCREATEVERTEXARRAYSPROC __glCreateVertexArrays;
extern PFNGLDISABLEVERTEXARRAYATTRIBPROC __glDisableVertexArrayAttrib;
extern PFNGLENABLEVERTEXARRAYATTRIBPROC __glEnableVertexArrayAttrib;
extern PFNGLVERTEXARRAYELEMENTBUFFERPROC __glVertexArrayElementBuffer;
extern PFNGLVERTEXARRAYVERTEXBUFFERPROC __glVertexArrayVertexBuffer;
extern PFNGLVERTEXARRAYVERTEXBUFFERSPROC __glVertexArrayVertexBuffers;
extern PFNGLVERTEXARRAYATTRIBBINDINGPROC __glVertexArrayAttribBinding;
extern PFNGLVERTEXARRAYATTRIBFORMATPROC __glVertexArrayAttribFormat;
extern PFNGLVERTEXARRAYATTRIBIFORMATPROC __glVertexArrayAttribIFormat;
extern PFNGLVERTEXARRAYATTRIBLFORMATPROC __glVertexArrayAttribLFormat;
extern PFNGLVERTEXARRAYBINDINGDIVISORPROC __glVertexArrayBindingDivisor;
extern PFNGLGETVERTEXARRAYIVPROC __glGetVertexArrayiv;
extern PFNGLGETVERTEXARRAYINDEXEDIVPROC __glGetVertexArrayIndexediv;
extern PFNGLGETVERTEXARRAYINDEXED64IVPROC __glGetVertexArrayIndexed64iv;
extern PFNGLCREATESAMPLERSPROC __glCreateSamplers;
extern PFNGLCREATEPROGRAMPIPELINESPROC __glCreateProgramPipelines;
extern PFNGLCREATEQUERIESPROC __glCreateQueries;
extern PFNGLGETQUERYBUFFEROBJECTI64VPROC __glGetQueryBufferObjecti64v;
extern PFNGLGETQUERYBUFFEROBJECTIVPROC __glGetQueryBufferObjectiv;
extern PFNGLGETQUERYBUFFEROBJECTUI64VPROC __glGetQueryBufferObjectui64v;
extern PFNGLGETQUERYBUFFEROBJECTUIVPROC __glGetQueryBufferObjectuiv;
extern PFNGLMEMORYBARRIERBYREGIONPROC __glMemoryBarrierByRegion;
extern PFNGLGETTEXTURESUBIMAGEPROC __glGetTextureSubImage;
extern PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC __glGetCompressedTextureSubImage;
extern PFNGLGETGRAPHICSRESETSTATUSPROC __glGetGraphicsResetStatus;
extern PFNGLGETNCOMPRESSEDTEXIMAGEPROC __glGetnCompressedTexImage;
extern PFNGLGETNTEXIMAGEPROC __glGetnTexImage;
extern PFNGLGETNUNIFORMDVPROC __glGetnUniformdv;
extern PFNGLGETNUNIFORMFVPROC __glGetnUniformfv;
extern PFNGLGETNUNIFORMIVPROC __glGetnUniformiv;
extern PFNGLGETNUNIFORMUIVPROC __glGetnUniformuiv;
extern PFNGLREADNPIXELSPROC __glReadnPixels;
extern PFNGLGETNMAPDVPROC __glGetnMapdv;
extern PFNGLGETNMAPFVPROC __glGetnMapfv;
extern PFNGLGETNMAPIVPROC __glGetnMapiv;
extern PFNGLGETNPIXELMAPFVPROC __glGetnPixelMapfv;
extern PFNGLGETNPIXELMAPUIVPROC __glGetnPixelMapuiv;
extern PFNGLGETNPIXELMAPUSVPROC __glGetnPixelMapusv;
extern PFNGLGETNPOLYGONSTIPPLEPROC __glGetnPolygonStipple;
extern PFNGLGETNCOLORTABLEPROC __glGetnColorTable;
extern PFNGLGETNCONVOLUTIONFILTERPROC __glGetnConvolutionFilter;
extern PFNGLGETNSEPARABLEFILTERPROC __glGetnSeparableFilter;
extern PFNGLGETNHISTOGRAMPROC __glGetnHistogram;
extern PFNGLGETNMINMAXPROC __glGetnMinmax;
extern PFNGLTEXTUREBARRIERPROC __glTextureBarrier;


//  GL_VERSION_4_6
#define glSpecializeShader __glSpecializeShader
#define glMultiDrawArraysIndirectCount __glMultiDrawArraysIndirectCount
#define glMultiDrawElementsIndirectCount __glMultiDrawElementsIndirectCount
#define glPolygonOffsetClamp __glPolygonOffsetClamp

extern PFNGLSPECIALIZESHADERPROC __glSpecializeShader;
extern PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC __glMultiDrawArraysIndirectCount;
extern PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC __glMultiDrawElementsIndirectCount;
extern PFNGLPOLYGONOFFSETCLAMPPROC __glPolygonOffsetClamp;
